### ISSUE TITLE
Consider hooking up a build server

### ISSUE THREAD

**Issue by chrisvest** [AdoptOpenJDK/jitwatch#142]
I've used Travis-CI on other projects and it works quite well. It supports multiple Java versions and can build PRs as well:

http://docs.travis-ci.com/user/languages/java/

**Comment by chriswhocodes** [comment]
@chrisvest Does this one work for you? https://adopt-openjdk.ci.cloudbees.com/job/jitwatch/

**Comment by chrisvest** [comment]
@chriswhocodes Not really. The nice build feedback on PRs is what I'm after, like the clickable crosses and checkmarks you see e.g. here: https://github.com/jruby/jruby/pulls

**Comment by chriswhocodes** [comment]
JITWatch now has it's own Jenkins CI: http://chriswhocodes.com:8080/
Will take a look at the JRuby CI for ideas for improving it.
