### ISSUE TITLE
Jitwatch doesn't correctly parse valid log lines with unusual class names

### ISSUE THREAD

**Issue by RichardWarburton** [AdoptOpenJDK/jitwatch#150]
I actually encountered this bug when playing around with Valhalla, but I think the class name "ArrayList${0=I}" is valid even in earlier JVM versions. It might be worth looking at https://blogs.oracle.com/jrose/entry/symbolic_freedom_in_the_vm - which points out that there are a lot of class names which are valid bytecode, but not valid source code.

Here's a log:

ClassNotFoundException: 'sun.misc.JavaLangRefAccess'
ClassNotFoundException: 'sun.util.locale.provider.EnLocaleDataMetaInfo'
Exception: 'sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo'
Exception: 'sun.util.resources.provider.NonEnLocaleDataMetaInfo'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$1'
ClassNotFoundException: 'valhalla.specializer.Specializer'
ClassNotFoundException: 'valhalla.specializer.TypeVariablesMapAttribute'
ClassNotFoundException: 'valhalla.specializer.BytecodeMappingAttribute'
ClassNotFoundException: 'valhalla.specializer.WhereAttribute'
ClassNotFoundException: 'valhalla.specializer.Specializer$ManglingAdapter'
ClassNotFoundException: 'valhalla.specializer.TypeVariablesMapAttribute$Entry'
ClassNotFoundException: 'valhalla.specializer.TVarExtractor'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$ForType'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$WithTypeParams'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$ForClass'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$ForClass$$Lambda$1/558638686'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$ForType$ClassFrame'
ClassNotFoundException: 'java.util.BitSet$$Lambda$2/1989780873'
ClassNotFoundException: 'valhalla.specializer.Specializer$ManglingAdapter$$Lambda$3/931919113'
ClassNotFoundException: 'valhalla.specializer.SignatureEraser'
ClassNotFoundException: 'valhalla.specializer.Specializer$MethodAttributeExtractor'
ClassNotFoundException: 'valhalla.specializer.Specializer$ManglingMethodVisitor'
ClassNotFoundException: 'valhalla.specializer.Specializer$ManglingMethodVisitor$$Lambda$4/2129789493'
ClassNotFoundException: 'java.util.stream.MatchOps$$Lambda$5/1791741888'
ClassNotFoundException: 'valhalla.specializer.ClassNameRewriter'
ClassNotFoundException: 'valhalla.specializer.PreRewriter'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$ForMethod'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$ForMethod$$Lambda$6/1531448569'
ClassNotFoundException: 'valhalla.specializer.SignatureSpecializer$ForMethod$$Lambda$7/1867083167'
ClassNotFoundException: 'java.net.URLClassLoader$1$1'
ClassNotFoundException: 'ArrayList${0=I}'
Could not parse line 8559 : java.lang.invoke.LambdaForm$BasicType access$100 (Ljava.lang.invoke.LambdaForm$BasicType;)Ljava.lang.Class; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 8642 : java.lang.invoke.LambdaForm$BasicType basicTypeChar ()C : MetaMember not found for java.lang.invoke.LambdaForm$BasicType basicTypeChar ()C
Could not parse line 8892 : java.lang.invoke.LambdaForm$BasicType access$100 (Ljava.lang.invoke.LambdaForm$BasicType;)Ljava.lang.Class; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 9249 : java.lang.invoke.LambdaForm$BasicType basicTypeChar ()C : MetaMember not found for java.lang.invoke.LambdaForm$BasicType basicTypeChar ()C
Could not parse line 17414 : java.lang.invoke.LambdaForm$BasicType basicType (C)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 18483 : java.lang.invoke.LambdaForm$Name type ()Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 18866 : java.lang.invoke.LambdaForm$BasicType basicTypeClass ()Ljava.lang.Class; : MetaMember not found for java.lang.invoke.LambdaForm$BasicType basicTypeClass ()Ljava.lang.Class;
Could not parse line 19678 : java.lang.invoke.LambdaForm$BasicType basicType (C)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 20656 : java.lang.invoke.LambdaForm$BasicType basicType (Ljava.lang.Class;)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 21335 : java.lang.invoke.LambdaForm$BasicType basicType (Ljava.lang.Class;)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 21566 : java.lang.invoke.LambdaForm$Name type ()Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 23992 : java.lang.invoke.LambdaForm parameterType (I)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 24115 : java.lang.invoke.LambdaForm parameterType (I)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 27301 : java.lang.invoke.LambdaForm$BasicType basicTypeClass ()Ljava.lang.Class; : MetaMember not found for java.lang.invoke.LambdaForm$BasicType basicTypeClass ()Ljava.lang.Class;
Could not parse line 50357 : java.lang.invoke.LambdaForm argument (ILjava.lang.invoke.LambdaForm$BasicType;)Ljava.lang.invoke.LambdaForm$Name; : Could not parse types: ILjava.lang.invoke.LambdaForm$BasicType;
Could not parse line 51681 : java.lang.invoke.LambdaForm parameter (I)Ljava.lang.invoke.LambdaForm$Name; : MetaMember not found for java.lang.invoke.LambdaForm parameter (I)Ljava.lang.invoke.LambdaForm$Name;
Could not parse line 56441 : java.lang.invoke.LambdaForm argument (ILjava.lang.invoke.LambdaForm$BasicType;)Ljava.lang.invoke.LambdaForm$Name; : Could not parse types: ILjava.lang.invoke.LambdaForm$BasicType;
Could not parse line 56558 : java.lang.invoke.LambdaForm parameter (I)Ljava.lang.invoke.LambdaForm$Name; : MetaMember not found for java.lang.invoke.LambdaForm parameter (I)Ljava.lang.invoke.LambdaForm$Name;
Could not parse line 61307 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 61517 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 61519 : ArrayList${0=I} add (I)V : Could not split signature with regex: 'ArrayList${0=I} add (I)V'
Could not parse line 61520 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 61804 : ArrayList${0=I} add (I)V : Could not split signature with regex: 'ArrayList${0=I} add (I)V'
Could not parse line 61806 : ArrayList${0=I} size ()I : Could not split signature with regex: 'ArrayList${0=I} size ()I'
Could not parse line 62305 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 62307 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 63059 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 63145 : ArrayList${0=I} size ()I : Could not split signature with regex: 'ArrayList${0=I} size ()I'
Could not parse line 64364 : ArrayList${0=I} add (I)V : Could not split signature with regex: 'ArrayList${0=I} add (I)V'
Could not parse line 65517 : ArrayList${0=I} add (I)V : Could not split signature with regex: 'ArrayList${0=I} add (I)V'
Could not parse line 74384 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 75873 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 76959 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 77678 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 79732 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 84003 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 84006 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 91662 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 105869 : java.lang.invoke.LambdaForm$BasicType access$100 (Ljava.lang.invoke.LambdaForm$BasicType;)Ljava.lang.Class; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 105988 : java.lang.invoke.LambdaForm$BasicType basicTypeChar ()C : MetaMember not found for java.lang.invoke.LambdaForm$BasicType basicTypeChar ()C
Could not parse line 107609 : java.lang.invoke.LambdaForm$BasicType basicType (C)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 107990 : java.lang.invoke.LambdaForm$BasicType basicType (Ljava.lang.Class;)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 108072 : java.lang.invoke.LambdaForm$Name type ()Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 108530 : java.lang.invoke.LambdaForm parameterType (I)Ljava.lang.invoke.LambdaForm$BasicType; : Could not parse types: Ljava.lang.invoke.LambdaForm$BasicType;
Could not parse line 109170 : java.lang.invoke.LambdaForm$BasicType basicTypeClass ()Ljava.lang.Class; : MetaMember not found for java.lang.invoke.LambdaForm$BasicType basicTypeClass ()Ljava.lang.Class;
Could not parse line 113805 : java.lang.invoke.LambdaForm argument (ILjava.lang.invoke.LambdaForm$BasicType;)Ljava.lang.invoke.LambdaForm$Name; : Could not parse types: ILjava.lang.invoke.LambdaForm$BasicType;
Could not parse line 113843 : java.lang.invoke.LambdaForm parameter (I)Ljava.lang.invoke.LambdaForm$Name; : MetaMember not found for java.lang.invoke.LambdaForm parameter (I)Ljava.lang.invoke.LambdaForm$Name;
Could not parse line 114926 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 115008 : ArrayList${0=I} add (I)V : Could not split signature with regex: 'ArrayList${0=I} add (I)V'
Could not parse line 115194 : ArrayList${0=I} size ()I : Could not split signature with regex: 'ArrayList${0=I} size ()I'
Could not parse line 116717 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 116964 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 119727 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 119992 : ArrayList${0=I} add (I)V : Could not split signature with regex: 'ArrayList${0=I} add (I)V'
Could not parse line 120744 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'
Could not parse line 122265 : ArrayList${0=I} ensureCapacity (I)V : Could not split signature with regex: 'ArrayList${0=I} ensureCapacity (I)V'
Could not parse line 123623 : ArrayList${0=I} toString ()Ljava.lang.String; : Could not split signature with regex: 'ArrayList${0=I} toString ()Ljava.lang.String;'

**Comment by chriswhocodes** [comment]
Thanks Richard, I'll copy the patterns from http://hg.openjdk.java.net/mlvm/mlvm/file/tip/netbeans/meth/test/sun/invoke/util/BytecodeNameTest.java into my unit tests for ParseUtil.

**Comment by chriswhocodes** [comment]
Hi Richard, 

Regular expressions in ParseUtil for LogCompilation now meet http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.2

Added a regression test and this should now parse but not sure this is the entire fix (it might try to Class.forName("ArrayList${0=I}") to enumerate the methods which will fail.

Would you mind testing again and sending me the hotspot.log?

I've joined the valhalla-dev mailing list to keep tabs on upcoming language changes.

Thanks,

Chris

**Comment by chriswhocodes** [comment]
Closing as I believe this is now fixed by https://github.com/AdoptOpenJDK/jitwatch/commit/858618fdd93b632b0b45bb695a43bbae9183a472
