### ISSUE TITLE
Cannot use jar files as source

### ISSUE THREAD

**Issue by jeremyongithub** [AdoptOpenJDK/jitwatch#164]
When adding jar files in the "sources" configuration,  jitwatch is not able to link the code to that source. Only folders seems to work.

**Comment by chriswhocodes** [comment]
Hi, please can you provide some more details?

I've tested this with the JDK's src.zip and also by making a jar file of the JITWatch sources and mounting that when parsing the demo hotspot.log and both were able to open the source in the TriView.

Do your source packages start at the root of your jar or are they buried deeper?

Thanks,
Chris

**Comment by jeremyongithub** [comment]
Hi,

They are buried deeper, following the package convention. I looked at this a bit more today and i got the following behaviour. I used your example "SampleInliningTest". 

If I leave it in the default package, I have two jars:

```
$ jar tf simple.jar
META-INF/
META-INF/MANIFEST.MF
SimpleInliningTest.class
$ jar tf simple.src.jar
META-INF/
META-INF/MANIFEST.MF
SimpleInliningTest.java
```

In this case, I generate the log and point the config to the two relevant jars and I can see the source fine.

However, If i don't use the default package, I have this:
```
 $ jar tf simple.jar
META-INF/
META-INF/MANIFEST.MF
com/test/SimpleInliningTest.class
$ jar tf simple.src.jar
META-INF/
META-INF/MANIFEST.MF
com/test/SimpleInliningTest.java
```
If I generate the log, load it in jitwatch and add the jars in the relevant sections in the config box, I can't see the source in the tri-view (but I can see the bytecode fine).

Cheers,
Jeremy

**Comment by chriswhocodes** [comment]
Hi Jeremy,

Can you email me the jars you created please?

chris AT chrisnewland DOT com

Thanks

**Comment by jeremyongithub** [comment]
Hi,

Actually I could not reproduce this on Linux and that got me thinking why it didn't work on windows. I think it's because a jar file uses '/' as a file separator. The function *"org.adoptopenjdk.jitwatch.loader.ResourceLoader.readFileFromZip(File, String)"* gets the fileName originally from *"org.adoptopenjdk.jitwatch.loader.ResourceLoader.getSource(MetaClass, List<String>)"*:

```
String filename = fqName.replace(S_DOT, File.separator) + S_DOT + suffix;
```

On Windows, File.separator is '\', which would not work while opening a jar file. 

I think we can safely assume that jar files will always use "/" as a separator for compatibility reasons, so I suggest the following change in *org.adoptopenjdk.jitwatch.loader.ResourceLoader.getSource(String, List<String>)*:

```
source = readFileFromZip(lf, fileName.replace(S_BACKSLASH, S_SLASH));
```

**Comment by chriswhocodes** [comment]
Hi Jeremy,

I think you're right. I'll make a regression test and then fix. I'll also try to replace File.separator with Java 7 Paths where possible.

Many thanks,

Chris

**Comment by chriswhocodes** [comment]
Fixed + unit test https://github.com/AdoptOpenJDK/jitwatch/commit/7ba9986cd59b4b715733115521e76ff17a7c2699
