### ISSUE TITLE
Reliance on user.dir may cause issues on read-only filesystems

### ISSUE THREAD

**Issue by jeremyongithub** [AdoptOpenJDK/jitwatch#165]
When installing jitwatch to read-only filesystem, we can get exceptions when saving the configuration. 

user.dir can get the value of the installation directory and cause issue if not writeable. is it possible to use the Preference framework?

**Comment by chriswhocodes** [comment]
Hi, this seems like quite a rare use case to justify rewriting the JITWatch config system.

I've put in a quick fix: https://github.com/AdoptOpenJDK/jitwatch/commit/9e9936243cb43b318a52cf793b1dead7f5ac01c5.

You can now override the JITWatch properties file using the JVM system property switch
```
-Djitwatch.config.file=somefile
```
