### ISSUE TITLE
No source code shown in JITWatch in a project

### ISSUE THREAD

**Issue by wei79** [AdoptOpenJDK/jitwatch#166]
First, I tried a simple helloworld.java and source code shown in JITWatch successfully:
$ javac -g helloworld.java
$ java -XX:+UnlockDiagnosticVMOptions -XX:+LogCompilation -XX:+TraceClassLoading -XX:+PrintAssembly hello

Then I tried SPECjbb benchmark, and added a "-g" option to build.xml to rebuild the project. 
    <compilerarg line="-g -J-Xms128m -J-Xmx512m" />
and changed run.sh to add following option: 
  -XX:+UnlockDiagnosticVMOptions -XX:+LogCompilation -XX:+TraceClassLoading -XX:+PrintAssembly 
$ ant clean; 
$ ant
$ ./run.sh 
There is no source code after importing log file to JITWatch.

**Comment by chriswhocodes** [comment]
Hi Wei,

Please can you confirm that you have imported the SPECjbb source (folder? jar?) into the JITWatch config? (JITWatch can't locate sources automatically).

If you've done that, please can you make sure you are using the latest JITWatch code and check that the source is mounted from the root of the package tree.

E.g. if you are mounting a source jar called src.zip and expecting it to contain class foo.bar.Baz.java then it's path inside the jar is /foo/bar/Baz.java

It looks like the SPECjbb benchmark is not freely available so I can't check it myself.

Thanks,

Chris

**Comment by wei79** [comment]
Hi Chris, 
  I have added source code folder into the JITWatch config and latest JITWatch. Will try to change to different configuration tomorrow. 

Regards!
wei

**Comment by chriswhocodes** [comment]
Hi Wei,

Do you still have problems loading source code in JITWatch?

Let me know if I can close this issue?

Thanks

**Comment by tramchamploo** [comment]
have some problem here

**Comment by chriswhocodes** [comment]
Hi @tramchamploo,
Please can you open a new issue and give as much detail as possible on how to recreate the problem?
Thanks
