### ISSUE TITLE
Could not find artifact com.oracle:javafx:jar:8 at specified path

### ISSUE THREAD

**Issue by michaeltandy** [AdoptOpenJDK/jitwatch#170]
Just a quick note - this isn't really a fault of jitwatch, but it might be relevant to other jitwatch users.

I ran `mvn clean compile test exec:java` on Ubuntu 15.04 after installing OpenJDK 8 as packaged with Ubuntu, and got this error:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.500s
[INFO] Finished at: Thu Jun 18 22:16:07 BST 2015
[INFO] Final Memory: 10M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jitwatch: Could not resolve dependencies for project org.adoptopenjdk.jitwatch:jitwatch:jar:1.0.0-SNAPSHOT: Could not find artifact com.oracle:javafx:jar:8 at specified path /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jfxrt.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

mtandy@mtandy-desktop:~/jitwatch$ java -version
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Turns out the version of OpenJDK 8 packaged with Ubuntu 15.04 doesn't include javafx. I switched to `oracle-java8-installer` after adding the repository `ppa:webupd8team/java` and I was able to successfully run jitwatch.

**Comment by chriswhocodes** [comment]
Hi Michael,

Thanks for the information.

OpenJDK doesn't include JavaFX but there is an open source implementation called OpenJFX.

I don't know if there is an Ubuntu package for OpenJFX but I run a CI server here: http://108.61.191.178/ that produces nightly builds of OpenJFX for Linux and OSX that can be dropped into OpenJDK to provide the missing JavaFX functionality.

Cheers,

Chris
