### ISSUE TITLE
Assembly not found for Nashorn classes

### ISSUE THREAD

**Issue by szegedi** [AdoptOpenJDK/jitwatch#171]
I added a Nashorn class dump directory and a HotSpot log as a tar.gz to https://www.dropbox.com/s/f7d22fmdvqvumye/earley-boyer-jitwatch.tgz (if you unpack it, put it into a tmp directory first, as it has no top-level dir…)

It's a result of running Octane earley-boyer test. It seems that for most script classes, jitwatch claims that assembly is not found. It might have something to do with lazy compilation (this is with -ot=false). It also - weirdly - does that for e.g. idk.nashorn.internal.objects.Global (and possibly some other classes) that are not dynamically generated, but just plainly part of the nashorn.jar.

**Comment by chriswhocodes** [comment]
Hi Attila,

Thanks for uploading that tgz, I'll try and work out what's happening here.

Please can you provide the exact command line you used to run the test?

Thanks,

Chris

**Comment by szegedi** [comment]
Here's the command line, as executed in a nashorn source directory (e.g. jdk9/nashorn):
```
java jdk.nashorn.tools.Shell -scripting --dump-debug-dir=classdump test/script/basic/run-octane.js -- earley-boyer --iterations 10 --verbose
```
You'll have to have octane in `test/script/externals/octane`; the easiest way to get it there is 
```
cd make
ant get-octane
```

**Comment by chriswhocodes** [comment]
Hi Attila,

I've encountered the same thing. With latest jdk9dev from hg and the following command line I get a 407M hotspot.log file containing assembly:

`java -XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:+PrintAssembly jdk.nashorn.tools.Shell -scripting --dump-debug-dir=classdump  test/script/basic/run-octane.js -- earley-boyer --iterations 10 --verbose`

But when I add -ot=false I get a 10M hotspot.log with no assembly:

`java -XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:+PrintAssembly jdk.nashorn.tools.Shell -scripting --dump-debug-dir=classdump -ot=false test/script/basic/run-octane.js -- earley-boyer --iterations 10 --verbose`

The smaller log file contains the XML I'd expect to find with JIT compilations (nmethod and task compile_id=.. tags) and JITWatch shows a decreasing code cache in the Code Cache chart but the assembly is not emitted.

I'll keep digging but I think this one lies in VM land!

**Comment by chriswhocodes** [comment]
Hi Attila,
A lot of JDKs have passed under the bridge so I'm going to close this issue and will do some testing with Nashorn and recent JITWatch / JDK builds.
