### ISSUE TITLE
style.css missing from generated JAR (ant build)

### ISSUE THREAD

**Issue by mhaupt** [AdoptOpenJDK/jitwatch#172]
After building with ant, running via `ant run` or `launchUI.sh` fails because the `style.css` style sheet cannot be found. Suggestion: add `*.css` to the fileset used to generate the JITwatch JAR file in `build.xml`.

**Comment by chriswhocodes** [comment]
Fixed by a9c4ef881d3adbf609bdab4e3dbbec9ce90f1d26
