### ISSUE TITLE
New windows placed on wrong screen

### ISSUE THREAD

**Issue by hns** [AdoptOpenJDK/jitwatch#173]
I'm running JITWatch on Ubuntu 14.04 with a dual monitor setup. When JITWatch opens new windows they are always placed on the left screen, even though the main window is on the right screen. 

New windows should be placed on the same screen as the main screen.

**Comment by chriswhocodes** [comment]
Fixed by 7daa1b24f48600cfaa0844d8e3b95f8d62932277 and tested on OSX and Debian. Please could you test on Ubuntu and close the issue if this fix works for you? Thanks

**Comment by hns** [comment]
Placement of new windows is now fine with my setup. I do see a short flicker of the new window on the other screen, but that's not a big deal. I'm playing around a bit to see if I can get rid of this, but consider the issue closed. Thanks for the quick fix!
