### ISSUE TITLE
Code Suggestions

### ISSUE THREAD

**Issue by karussell** [AdoptOpenJDK/jitwatch#178]
The code suggestions are nice. But some of them I do not fully understand or would need to know a bit background information to make them actually helpful, or include some proposed actions to fix that problem. Is it e.g. planned to link some web resources into it?

For example:
 * `was not inlined for reason: 'no static binding'. The callee is known but there is no static binding so could not be inlined.`
 * `was not inlined for reason: 'already compiled into a medium method'`

Also my very first suggestion is about a class (Hashtable) which is used in my code very rarely and not that often like the printed invocations of 30 871 365! Is there a way to find out one or more sources causing a suggestion?

**Comment by chriswhocodes** [comment]
Hi, sorry for the delay in replying. 30M invocations on Hashtable if it's not part of your application sounds suspicious. Any chance you could email me the zipped hotspot log file that gave you that suggestion? chris@chrisnewland.com

Yes, I need to expand the explanations on some of the "reasons" in the hotspot log.

**Comment by karussell** [comment]
Sorry for the very late reply ... I'll hopefully have time and re-do this again!

**Comment by chriswhocodes** [comment]
Hi, no worries, all feedback is very appreciated!
I'm at a hackday tomorrow and should finish off a lot of uncommitted JITWatch stuff I've been sitting on.

**Comment by chriswhocodes** [comment]
Hi, I'm going to close this issue as I don't have a log file to investigate.
Please re-open with a hotspot log if the problem still occurs.
