### ISSUE TITLE
Latest JAR cannot be downloaded from CI (anonymously)

### ISSUE THREAD

**Issue by rvansa** [AdoptOpenJDK/jitwatch#192]
Since I don't have any account in CI, I can't get to the built artifacts with anonymous access.

**Comment by chriswhocodes** [comment]
Hi Radim,
I'll see if I can get the artifacts made available.
@neomatrix369 can you advise?
Thanks,
Chris

**Comment by neomatrix369** [comment]
Are you talking about the jitwatch artifacts on cloudbees ?

**Comment by rvansa** [comment]
@neomatrix369 Yes, the link on the end of [wiki page](https://github.com/AdoptOpenJDK/jitwatch/wiki) leads to cloudbees.

**Comment by neomatrix369** [comment]
Unfortunately at the time of the setting of that Jenkins job we didn't make
it such it produced artifacts - @chris do you have a link to your CI
servers where they are build regularly ?

On Mon, 4 Jan 2016 at 09:03 Radim Vansa <notifications@github.com> wrote:

> @neomatrix369 <https://github.com/neomatrix369> Yes, the link on the end
> of wiki page <https://github.com/AdoptOpenJDK/jitwatch/wiki> leads to
> cloudbees.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AdoptOpenJDK/jitwatch/issues/192#issuecomment-168615988>
> .
>
-- 
@theNeomatrix369 <http://twitter.com/theNeomatrix369>*  |  **Blog
<http://neomatrix369.wordpress.com/>**  |  *LJC Associate & LJC Advocate
(@adoptopenjdk & @adoptajsr programs)
*Meet-a-Project - *MutabilityDetector
<https://github.com/MutabilityDetector>*  |  **Bitbucket
<https://bitbucket.org/neomatrix369>* * |  **Github
<https://github.com/neomatrix369>* * |  **LinkedIn
<http://uk.linkedin.com/pub/mani-sarkar/71/a77/39b>*
*Come to Devoxx UK 2016:* http://www.devoxx.co.uk/

*Don't chase success, rather aim for "Excellence", and success will come
chasing after you!*

**Comment by chriswhocodes** [comment]
Hi Radim,

Could you let me know if having JITWatch in maven central would solve your problem?

It's quite tricky to make an executable "uber" jar for JITWatch because of it's dependency on the JDK's tools.jar

Let me know and I'll make finishing the maven central work my next task.

Cheers,

Chris

@neomatrix369 I'll try and get a public Jenkins for JITWatch available tonight.

**Comment by rvansa** [comment]
@chriswhocodes In fact it's not a problem for me; I can just clone the repo and build it myself. But I found rather confusing that you advertise the 'lastest version download' on wiki and it's not possible.

**Comment by chriswhocodes** [comment]
Hi Radim,
JITWatch finally has its own Jenkins CI that's on a box I control: http://chriswhocodes.com:8080/
The build products should be available read-only to anon users.

**Comment by rvansa** [comment]
Thanks for the info.
