### ISSUE TITLE
Failing to parse assembly

### ISSUE THREAD

**Issue by rvansa** [AdoptOpenJDK/jitwatch#193]
Hi, when running master (`e9d8ddc7436d862077892c367923043b87953c20`) with these JVM options `-XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:+PrintAssembly -XX:+PrintInlining -XX:LogFile=assw.log` on Oracle JDK 1.8.0_60 I got some errors when trying to parse the log:
https://gist.github.com/rvansa/0a2df1e4d712cf9b6f21

Then, in JitWatch UI (in TriView) I can't see the native assembly, and it tells me there's none, although the method is marked as compiled. In compile chain, I can see that some methods are compiled and/or inlined, but the root method is always non-compiled. Also I miss some method invocations in the chain - not sure if this is a bug or feature (method A.foo() always calls interface B.bar(), A.foo() is in the graph as inlined and compiled, but there's no link to B.bar()).

If I omit `-XX:+PrintInlining`, I can't see the compile chain but assembly works. I guess that my logs contain entries interleaved in a weird way, since I can see things like:
```
<writer thread='139785240991488'/>
0x30(%rsp)
  0x00007f2251336bc7: 
<writer thread='139785256470272'/>
    @ 9   java.lang.ClassLoader::
<writer thread='139785240991488'/>
lea    0x30(%rsp),%r14
  0x00007f2251336bcc: mov    
<writer thread='139785256470272'/>
getClassLoader (11 bytes)
<writer thread='139785240991488'/>
%r14,%rsi                                       ; OopMap{[0]=Oop [48]=Oop off=79}
  0x00007f2251336bcf: 
<writer thread='139785256470272'/>
                          
<writer thread='139785240991488'/>
mov    $0x7f2251336bcf,%r10
                                                
<writer thread='139785256470272'/>
          @ 7  
```

Anyway, thanks for working on JITWatch, it's a really cool tool!

**Comment by chriswhocodes** [comment]
Hi Radim,

I didn't expect anyone to use -XX:+PrintInlining with -XX:+LogCompilation so my parser currently doesn't handle that as you've seen ;)

Could you post a gist without the PrintInlining and I'll try and work out why the compile chain isn't as you expect?

Thanks,

Chris

**Comment by rvansa** [comment]
@chriswhocodes Ah, my bad then! After removing the PrintInlining, I've looked on the compile chain for few methods and it popped up correctly. For some methods it won't show up, although these are compiled; could that be because they're never invoked (they're used only as inlined)? And is it expected that the interface call is not shown? The corresponding assembly is
```
0x00007f74e542efcf: callq 0x00007f74e5046220  ; OopMap{rbp=Oop [0]=Oop [8]=Oop [16]=Oop [32]=Oop off=116}
                                              ;*invokeinterface visitPutKeyValueCommand
                                              ; - org.infinispan.commands.write.PutKeyValueCommand::acceptVisitor@3 (line 73)
                                              ; - org.infinispan.interceptors.base.CommandInterceptor::invokeNextInterceptor@6 (line 99)
                                              ; - org.infinispan.interceptors.EntryWrappingInterceptor::invokeNextAndApplyChanges@3 (line 499)
                                              ;   {virtual_call}
```

**Comment by rvansa** [comment]
Also, the compiled methods in compile chain and in the main window don't seem to match: http://snag.gy/nmAu1.jpg

**Comment by chriswhocodes** [comment]
Hi, this sounds like a parsing bug but I'm going to have to close this issue as I don't have a clean HotSpot log to try and track it down.
Please feel free to upload a log file and I'll investigate. Thanks.
