### ISSUE TITLE
JVM not in-lining the hot method !

### ISSUE THREAD

**Issue by tejaghali** [AdoptOpenJDK/jitwatch#198]
HI ,

 I was running the following java class with below vm args. However when i view the output hotspot log file , found that assembly compliled add method and says inline - actually it hasn't done the inlining. Please find attached hotspot log file. However if i run the same program on different machine in-lining is happening. So there is something to do with assembler instruction. (Both the machines that i ran are using amd64 assembly processor), I am clueless why there is distinction in behavior on different machines, Jitwatch on my home machine perfectly says that add method is inlined - however jitwatch on different machine reports the method as not inlined . Any help is greatly appreciated.  
[hotspot.txt](https://github.com/AdoptOpenJDK/jitwatch/files/80912/hotspot.txt)

Where can i find definitions of (JI) J , (J) J etc. Thanks in advance for any help . 
eg:  # {method} 'bigMethod' '(JI)J' in '/InliningChains'

-XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:LogFile=E:\Session\sample2.log -XX:+PrintAssembly -XX:-BackgroundCompilation -XX:CompileThreshold=100 -XX:PrintAssemblyOptions=intel -XX:-UseCompressedOops -XX:+Inline -XX:+PrintInlining

public class SimpleInliningTest{
    public SimpleInliningTest()  {
       int sum = 0;
        long millis = System.currentTimeMillis();
        long nanos = System.nanoTime();
        for (int i = 0 ; i < 1000000; i++) {
            sum = this.add(sum, 1); // 63 hex
        }
        System.out.println(System.currentTimeMillis() - millis);
        System.out.println(System.nanoTime() - nanos);
        System.out.println("Sum:" + sum);
    }
    public int add(int a, int b)    {
        return a + b;
    }
    public static void main(String[] args)    {
        new SimpleInliningTest();
    }
}

**Comment by chriswhocodes** [comment]
Hi,
If you want to do microbenchmarking properly it's well worth learning to use JMH: http://openjdk.java.net/projects/code-tools/jmh/

Having said that, I would expect your code to inline method "add".

Please remove switch -XX:+PrintInlining when creating a log for JITWatch. Using -XX:+LogCompilation is enough and PrintInlining output will probably confuse the parser.

You can find the list of type identifiers in the Java language spec: http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3 or check the JITWatch source file src/main/java/org/adoptopenjdk/jitwatch/util/ParseUtil.java:

```
public static final char TYPE_SHORT = 'S';
public static final char TYPE_CHARACTER = 'C';
public static final char TYPE_BYTE = 'B';
public static final char TYPE_VOID = 'V';
public static final char TYPE_LONG = 'J';
public static final char TYPE_DOUBLE = 'D';
public static final char TYPE_BOOLEAN = 'Z';
public static final char TYPE_INTEGER = 'I';
public static final char TYPE_FLOAT = 'F';
```
Cheers,

Chris

**Comment by tejaghali** [comment]
Hi Chris,

Thanks A-lot for the quick response  , i tried running the program without printInlining option - it did not help. 

When i was going through assemblies of inlined and non inlined hotspot log file i noticed difference in assembly code - in case of non inlined one i see extra assembly instructions being generated like data32 xchg ax,ax - Please find attachment for inlined and non-inlined hotspot log files.

Inlined call:
 0x00000000026de6e0: inc    %r14d              ;*iadd
                                                ; - com.atmos.SimpleInliningTest::add@2 (line 28)
                                                ; - com.atmos.SimpleInliningTest::&lt;init&gt;@24 (line 17)

Non-Inlined call:
 0x0000000002956c0c: data32 xchg ax,ax
  0x0000000002956c0f: call   0x00000000029190a0  ; OopMap{off=244}
                                                ;*invokevirtual add
                                                ; - com.atmos.src.SimpleInliningTest::&lt;init&gt;@24 (line 13)
                                                ;   {runtime_call}
  0x0000000002956c14: int3                      ;*invokevirtual add
                                                ; - com.atmos.src.SimpleInliningTest::&lt;init&gt;@24 (line 13)

(


[inline.txt](https://github.com/AdoptOpenJDK/jitwatch/files/80970/inline.txt)
[no_Inline.txt](https://github.com/AdoptOpenJDK/jitwatch/files/80971/no_Inline.txt)

)

**Comment by chriswhocodes** [comment]
Hi,

Your inlining code is running on JDK 1.7.0_79 (HotSpot version 24.79-b02)
Your non-inlining code is running on JDK 1.7.0_17-b02 (HotSpot version 23.7-b01)

I don't think you should expect identical JIT behaviour from different HotSpot releases.

Try running the same JVM on both machines?

Cheers,

Chris

**Comment by tejaghali** [comment]
HI Chris,

Seems like there is a bug with Hotspot version 23.7-b01 , I ran the program using hotspot version 24.79-b02 on the second machine and it inlined the add method without fail. 

Thanks a-lot for your support and i really appreciate you taking time to respond to my naive questions. :)

**Comment by chriswhocodes** [comment]
You're welcome.

Don't be afraid to ask questions, JIT compilation is hard and we're all learning :)
