### ISSUE TITLE
"Latest binaries from Jenkins" links in README.md are dead

### ISSUE THREAD

**Issue by arthurp** [AdoptOpenJDK/jitwatch#199]
The "JDK 1.7 binary" and "OpenJDK 8 binary" links in README.md are dead. Something about missing workspace.

**Comment by chriswhocodes** [comment]
Hi, yes sorry there is a problem with the AdoptOpenJDK CI server right now. I've removed the misleading links from the readme and will replace when a working CI is available.

For now please build from source using ant, maven, or gradle.
