### ISSUE TITLE
about compile log file

### ISSUE THREAD

**Issue by zouyx** [AdoptOpenJDK/jitwatch#200]
hi
i have generated compile log with vm options :-XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:LogFile=c:\mylogfile.log

but the compile log size just 1050KB

i opened it with JITWatch ,but just showed me JDK classes compile log .
it is not included  my classes
can you help me to reslove the problem?
thanks.

compile log as blew:

[compile log](https://github.com/AdoptOpenJDK/jitwatch/files/216813/new.3.txt)

**Comment by chriswhocodes** [comment]
Hi, the file you have attached contains only the text:

"hi i have generated compile log with vm options as -XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:LogFile=c:\mylogfile.log"

When running JITWatch you need to have the classes from your program available. This can either be by generating the log from your local machine (in which case JITWatch should be able to automatically locate the classes) or by adding the class folders or jars in the JITWatch config.

If you can upload your hotspot.log file then I'll try and help diagnose the problem.

Cheers,

Chris

**Comment by zouyx** [comment]
thanks for your reply.:no_mouth: 

hotspot log?
do you mean the hotspot file is  -XX:LogFile=c:\mylogfile.log?
the file which i have uploaded is -XX:LogFile=c:\mylogfile.log.

if not ,could you tell me how can i get the hotspot.log?

by the way ,i generated this file by idea compiler.


![pic](https://cloud.githubusercontent.com/assets/3828072/14493147/64734688-01b6-11e6-864d-811d5c6146bf.png)

**Comment by chriswhocodes** [comment]
Hi, yes that's the log I need.

The file you uploaded https://github.com/AdoptOpenJDK/jitwatch/files/216813/new.3.txt does not appear to be a hotspot log I'm afraid.

**Comment by zouyx** [comment]
i am so sorry for change the file name...........
:sob: 

thanks for help me to diagnose the problem.
:smile:

**Comment by chriswhocodes** [comment]
No problem, please let me know if you have any comments or feedback on JITWatch?

Thanks

**Comment by zouyx** [comment]
in fact the problem is this hotspot.log not included my classes,just included JDK classes..

when this log generating, this log's size increase to 12m once ,but suddenly down to 1m......

do you know why?

12m :
![pic1](https://cloud.githubusercontent.com/assets/3828072/14494725/e8582baa-01be-11e6-9621-868f2e4f31ae.jpg)

1m :
![pic2](https://cloud.githubusercontent.com/assets/3828072/14494756/18f86734-01bf-11e6-8afc-bce03e308d44.jpg)

**Comment by chriswhocodes** [comment]
Hi,

Can you tell me what JDK version you are using?

Usually while your program is running, HotSpot creates 1 temporary log file per compiler thread and combines them into hotspot.log (or whatever you rename it to) when the VM shuts down.

Please could you upload your HotSpot log file so I can take a look?

Thanks,

Chris

**Comment by zouyx** [comment]
hi chris.
thanks for your reply
i have knew the root problem.

the problem is ...i ran the compiler before only..

now i running the program.......
and the log keep printing...

thanks for your suggestion.
