### ISSUE TITLE
Compile chain looking backwards

### ISSUE THREAD

**Issue by danielshaya** [AdoptOpenJDK/jitwatch#210]
Hi Chris,

It would be a great if we could have a feature whereby we could have a compile chain that looked backwards.  i.e. we could see what methods caused the selected method to compile.  Similar to the 'call hierarchy' functionality you find in IDEs.

Thanks
Daniel

**Comment by chriswhocodes** [comment]
Hi, I'm closing all the issues except for the ones I'm actively working on.
