### ISSUE TITLE
Could not load main class

### ISSUE THREAD

**Issue by foxt7ot** [AdoptOpenJDK/jitwatch#212]
Steps:
Cloned repo
hit cmd> launchUI.bat
output:
```
lib\logback-classic-1.1.2.jar;lib\logback-core-1.1.2.jar;lib\slf4j-api-1.7.7.jar;C:\jdk1.8\lib\tools.jar;C:\jdk1.8\jre\lib\jfxrt.jar;core\target\classes;ui\target\classes
Error: Could not find or load main class ui.src.main.java.org.adoptopenjdk.jitwatch.launch.LaunchUI

```

Is it a known issue or am I doing something wrong?

**Comment by chriswhocodes** [comment]
Hi, did you build JITWatch using maven, ant, or gradle?

Cloning from GitHub just checks out the source code so you'll need to build the binaries on your local machine using one of the 3 supported build systems:

ant:
```ant clean compile test run```

maven:
```mvn clean compile test exec:java```

gradle:
```gradlew clean build run```

Once it has build then you can run using launchUI.bat

**Comment by foxt7ot** [comment]
Looks like I was doing it wrong. Thanks for clarification, I am closing the issue
