### ISSUE TITLE
Investigate bundling FCML hsdis library with JITWatch

### ISSUE THREAD

**Issue by chriswhocodes** [AdoptOpenJDK/jitwatch#222]
Free Code Manipulation Library (FCML) is an LGPL-licensed hsdis (HotSpot disassembly) plugin.

Investigate whether this can be distributed in binary form with JITWatch so that disassembly features work "out of the box" instead of users having to build their own hsdis binary using GNU binutils.

http://fcml-lib.com/index.html

**Comment by chriswhocodes** [comment]
I've contacted the FCML maintainer about this.

**Comment by garyttierney** [comment]
FWIW, I've been working on a Capstone (BSD-3-Clause) based [hsdis plugin](https://github.com/openjdk/jdk/compare/master...garyttierney:feat/capstone-hsdis?expand=1) for inclusion in the JDK.

This could be shipped with JITWatch quite easily.

**Comment by chriswhocodes** [comment]
Hi @garyttierney ,
That sounds awesome. The ability to support disassembly out of the box would be great.
Cheers,
Chris

**Comment by Brixomatic** [comment]
Any progress on this?

**Comment by chriswhocodes** [comment]
Hi, I'm closing all the issues except for the ones I'm actively working on.
