### ISSUE TITLE
jarScan.sh not work like the comment in the files.

### ISSUE THREAD

**Issue by cyberdak** [AdoptOpenJDK/jitwatch#233]
In jarScan.sh ,we can see this :
`
Scans ont or more jars for methods whose bytecodes size are above the default HotSpot inlining threshold for hot methods (325 bytes on Linux x86_64). Override the threshold with -DmaxMethodSize=n
`

but when i run this script,it tips me to add some mode like maxMethodSize and options.
I must manual append the mode and options  command to run this script.

It is seem we lost the key command on last command like

`"$JAVA_HOME/bin/java" -cp "$CLASSPATH" org.adoptopenjdk.jitwatch.jarscan.JarScan` "$@"

There are nothing about the key words "MaxMethodSize=325"

**Comment by chriswhocodes** [comment]
Thanks for the report. 
JarScan now has several new modes. Updated the script comment and param check so you get the correct usage if you run with 0 params.

Fixed in https://github.com/AdoptOpenJDK/jitwatch/commit/7cbe85f58dabf1086bb33195c313a00b55751a14
