### ISSUE TITLE
Missing quotes in launchUI.bat

### ISSUE THREAD

**Issue by JornVernee** [AdoptOpenJDK/jitwatch#235]
The `launchUI.bat` file contains the line:

    "%JAVA_HOME%\bin\java" -Djava.library.path=%JAVA_HOME%\lib\amd64 -classpath "%CLASSPATH%" org.adoptopenjdk.jitwatch.launch.LaunchUI

Note in particular the setting of the library path.

Since my `%JAVA_HOME%` contains spaces, I get the error:

    Error: Could not find or load main class Files\Java\jdk1.8.0_101\lib\amd64

When running this script. 

---
Quoting the library path like so:

    -Djava.library.path="%JAVA_HOME%\lib\amd64"

Solves this problem for me.

**Comment by chriswhocodes** [comment]
Fixed with https://github.com/AdoptOpenJDK/jitwatch/commit/a71092b8aa080c3bf3b9a1ef4222df78c29f3a9f

Thanks for letting me know.
