### ISSUE TITLE
NumberFormatException when loading assembly in TriView

### ISSUE THREAD

**Issue by JornVernee** [AdoptOpenJDK/jitwatch#236]
After adding the `-XX:+PrintAssembly` option to my `java` run command, and loading the produced log. I encountered a `NumberFormatException` when opening the TriView.

When loading the log and opening the TriView before I added the `PrintAssembly` option, I did not encounter this exception.

The specific method I was looking at was `public static char[] copyOfRange(char[],int,int)` in `java.util.Arrays`.

Here is the stack trace:

    Exception in thread "Thread-7" java.lang.NumberFormatException: For input string: "2fab0eeh0x0000000002fab08f"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at org.adoptopenjdk.jitwatch.model.assembly.AssemblyUtil.getValueFromAddress(AssemblyUtil.java:278)
        at org.adoptopenjdk.jitwatch.model.assembly.AssemblyLabels.instructionToLabel(AssemblyLabels.java:63)
        at org.adoptopenjdk.jitwatch.model.assembly.AssemblyLabels.newInstruction(AssemblyLabels.java:48)
        at org.adoptopenjdk.jitwatch.model.assembly.AssemblyUtil.createInstruction(AssemblyUtil.java:253)
        at org.adoptopenjdk.jitwatch.model.assembly.AssemblyUtil.parseAssembly(AssemblyUtil.java:135)
        at org.adoptopenjdk.jitwatch.core.AssemblyProcessor.complete(AssemblyProcessor.java:161)
        at org.adoptopenjdk.jitwatch.core.AssemblyProcessor.handleLine(AssemblyProcessor.java:101)
        at org.adoptopenjdk.jitwatch.core.HotSpotLogParser.parseAssemblyLines(HotSpotLogParser.java:387)
        at org.adoptopenjdk.jitwatch.core.HotSpotLogParser.parseLogFile(HotSpotLogParser.java:304)
        at org.adoptopenjdk.jitwatch.core.HotSpotLogParser.processLogFile(HotSpotLogParser.java:282)
        at org.adoptopenjdk.jitwatch.ui.JITWatchUI$1.run(JITWatchUI.java:205)
        at java.lang.Thread.run(Thread.java:745)

The assembly view shows: "Assembly not found. Was -XX:+PrintAssembly option used?".

Here is a gist of the log file: [Link](https://gist.github.com/JornVernee/822229ed596329c72305a90fc0228d6a)

I should note that instead of compiling `hsdis` myself (I could not get it to work (linker errors)), I downloaded a binary here: https://sourceforge.net/projects/fcml/files/fcml-1.1.1/hsdis-1.1.1-win32-amd64.zip/download?use_mirror=kent

**Comment by chriswhocodes** [comment]
Hi,

Thanks for the report and the gist.

It looks like at around line 1350 of the gist, your log file got a bit mangled:

```
0x0000000002fab089: ror     byte ptr [rax+0ffffffffffffffbeh],1h
                                                ;   {metadata(method data for {method} {0x0000000017483bf8} &apos;charAt&apos; &apos;(I)C&apos; in &apos;java/lang/String&apos;)}
  0x0000000002fab08c: clc
  0x0000000002fab08d: jno     2fab0eeh
  0x0000000002fab08f: Fatal error: Disassembling failed with error code: 15<nmethod compile_id='8' compiler='C1' level='3' entry='0x0000000002faaf80' size='1376' address='0x0000000002faae10' relocation_offset='288' insts_offset='368' stub_offset='816' scopes_data_offset='992' scopes_pcs_offset='1096' dependencies_offset='1352' nul_chk_table_offset='1360' method='java/lang/String charAt (I)C' bytes='29' count='2796' iicount='2796' stamp='2.084'/>
Decoding compiled method 0x0000000002fab390:
Code:
Argument 0 is unknown.RIP: 0x2fab4e0 Code size: 0x00000190
<writer thread='2720'/>
[Loaded java.lang.StringCoding from C:\Program Files\Java\jre1.8.0_101\lib\rt.jar]
<writer thread='6564'/>
[Entry Point]
[Constants]
  # {method} {0x0000000017621308} &apos;getProperties&apos; &apos;(I)I&apos; in &apos;java/lang/CharacterDataLatin1&apos;
  # this:     rdx:rdx   = &apos;java/lang/CharacterDataLatin1&apos;```

Which broke the parser and made it think the address was the concat of 2 lines: 2fab0eeh0x0000000002fab08f

I'll try and fix the parser to ignore this and carry on.

**Comment by JornVernee** [comment]
Thanks. It works every time when I leave out the `-XX:+PrintAssembly` option. I also tried to regenerate the log several times. (I would try to fix it manually, if I knew how).

**Comment by chriswhocodes** [comment]
Hi, I've been looking at this and your assembly is in Intel format, not AT&T. This is probably the default for the FCML disassembler you're using.
```
  0x0000000002fa061e: cmp     edx,r8d
  0x0000000002fa0621: mov     rax,1765b288h     ;   {metadata(method data for {method} {0x000000001756ae98} &apos;min&apos; &apos;(II)I&apos; in &apos;java/lang/Math&apos;)}
  0x0000000002fa062b: mov     rsi,108h
  0x0000000002fa0635: jnle    2fa0645h
  0x0000000002fa063b: mov     rsi,118h
  0x0000000002fa0645: mov     rdi,qword ptr [rax+rsi]
  0x0000000002fa0649: lea     rdi,[rdi+1h]
```

So even without the log mangling JITWatch won't be able to process this currently I'm afraid.

I'll bump up the priority for an Intel assembly parser as I'm getting a lot of requests for that and will still make a fix for the mangling.

**Comment by JornVernee** [comment]
Aha, sorry about that. I didn't really notice myself. I know AT&T syntax and it looked readable enough ;). 

Maybe it's also the result of me using the pre-compiled binary. I'll have another look at compiling `hsdis` myself.

**Comment by JornVernee** [comment]
Actually, I added the option `-XX:PrintAssemblyOptions:"AT&T"` to the run command and it works fine now.

**Comment by chriswhocodes** [comment]
Hi, I've added support for Intel assembly format now with https://github.com/AdoptOpenJDK/jitwatch/commit/1171c92d530b90ee9d7aa2e47d3639e321d2f357 and the log file you uploaded seems to display assembly fine (apart from where the log is broken).

Closing this issue, please re-open if you still have this problem.
