### ISSUE TITLE
Huge bug: latest jitwatch not showing compiled classes

### ISSUE THREAD

**Issue by pdeva** [AdoptOpenJDK/jitwatch#240]
The latest version of jitwatch simply doesnt show some of the compiled classes in the 'packages' tree. 
I have a version from about a month ago that does show them.

This is an enormous bug.

I am attaching the log to this bug.

It simply doesnt show the `com.yahoo.sketches.memory.MemoryPerformance` class or anything in the `com.yahoo` namespace for that matter...

[memtest.zip](https://github.com/AdoptOpenJDK/jitwatch/files/490885/memtest.zip)

**Comment by chriswhocodes** [comment]
Hi,
At a glance the log file looks valid and I see queued, task, and nmethod tags for MemoryPerformance class.

I see IDEA classes on your class path, are you running JITWatch inside IntelliJ or standalone?

I suspect an exception has occurred (probably while rendering the results). Can you upload the JITWatch application log (called jitwatch.out) please?

Thanks,

Chris

**Comment by chriswhocodes** [comment]
Can you confirm that you had the com.yahoo.* classes available to JITWatch when you processed this log file (either mounted in the JITWatch config, or in the same locations on your machine as when you generated the log) ?

JITWatch requires access to the class files referenced in the HotSpot log and will currently not show them in the tree if they could not be classloaded.

I have an enhancement planned to allow JITWatch to do its best when referenced classes aren't available. See https://github.com/AdoptOpenJDK/jitwatch/issues/215

**Comment by pdeva** [comment]
ok it seems the issue was indeed the .class file not being present.

i was surprised this is a requirement to even show the class in the hierarchy view.
