### ISSUE TITLE
moving mouse to left after right click closes menu

### ISSUE THREAD

**Issue by pdeva** [AdoptOpenJDK/jitwatch#242]
on windows 10 java 8

video shows all:
http://screencast.com/t/v6YK3r0dcRW

The menu is closing by itself when i move the cursor to the left...

**Comment by chriswhocodes** [comment]
Can't reproduce this on OSX or Linux and don't have access to a Win10 system. Possibly a JavaFX bug? Could you try and confirm with a SCCCE?
