### ISSUE TITLE
Support HiDPI displays

### ISSUE THREAD

**Issue by lemmy** [AdoptOpenJDK/jitwatch#245]
Fonts are too small on HiDPI displays which makes reading assembly even more difficult. ;-)

As a temporary workaround
- Add .root {-fx-font-size: 20pt;} to style.css
- Pass "-DmonospaceFontSize=22"

**Comment by chriswhocodes** [comment]
Thanks for the report. I've been requested to change the monospaced font from Courier New to FiraCode (https://github.com/tonsky/FiraCode) which is a heavier font for the same size.
I'll see how that looks and add a config option for font size.

**Comment by chriswhocodes** [comment]
Hi, I'm closing all the issues except for the ones I'm actively working on.
