### ISSUE TITLE
NCDFE when mvn exec:java is run without compile

### ISSUE THREAD

**Issue by chriswhocodes** [AdoptOpenJDK/jitwatch#249]
If you compile using `mvn clean compile` and then run `mvn exec:java` separately it will fail randomly with NoClassDefFound errors even though the classes are present in the mvn target folder.

Running with ./launchUI.sh (target/classes on classpath) runs fine.

Possibly a broken pom or bad maven plugin

**Comment by asgs** [comment]
If run those two commands separately, I get the error below. Interestingly, if I clean compile exec:java in one command, I could see the UI launching fine.

`[ERROR] Failed to execute goal on project jitwatch-ui: Could not resolve dependencies for project com.chrisnewland:jitwatch-ui:jar:1.0.1-SNAPSHOT: Could not find artifa
ct com.chrisnewland:jitwatch:jar:1.0.1-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project jitwatch-ui: Could not resolve dependencies for project com.chrisnewland:jitwa
tch-ui:jar:1.0.1-SNAPSHOT: Could not find artifact com.chrisnewland:jitwatch:jar:1.0.1-SNAPSHOT
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:220)`

Is that what you're also seeing? I didn't see any NCDFE yet.

**Comment by chriswhocodes** [comment]
Hi, when I run `mvn exec:java` separately from `mvn compile` then JITWatch launches and opens the main window but will then fail with a classpath related error such as a NoSuchMethodError or sometimes a NoClassDefFoundError caused by a ClassNotFoundException.

The root of the stack trace is always from one of my UI classes and the problem never occurs when I run using `mvn compile exec:java` together so I believe this is maven/classpath related.

```
chris@chris:/home/chris/jitwatch$ mvn exec:java
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] JITWatch Parent
[INFO] JITWatch Core
[INFO] JITWatch Ui
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JITWatch Parent 1.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ jitwatch-parent ---
[INFO] skipping execute as per configuration
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JITWatch Core 1.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ jitwatch ---
[INFO] skipping execute as per configuration
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JITWatch Ui 1.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ jitwatch-ui ---
[WARNING] 
java.lang.NoClassDefFoundError: org/adoptopenjdk/jitwatch/report/suggestion/SuggestionWalker
	at org.adoptopenjdk.jitwatch.ui.JITWatchUI.buildSuggestions(JITWatchUI.java:287)
	at org.adoptopenjdk.jitwatch.ui.JITWatchUI.handleReadComplete(JITWatchUI.java:267)
	at org.adoptopenjdk.jitwatch.core.HotSpotLogParser.parseLogFile(HotSpotLogParser.java:308)
	at org.adoptopenjdk.jitwatch.core.HotSpotLogParser.processLogFile(HotSpotLogParser.java:282)
	at org.adoptopenjdk.jitwatch.sandbox.Sandbox.runJITWatch(Sandbox.java:367)
	at org.adoptopenjdk.jitwatch.sandbox.Sandbox.runSandbox(Sandbox.java:174)
	at org.adoptopenjdk.jitwatch.ui.sandbox.SandboxStage.runSandbox(SandboxStage.java:559)
	at org.adoptopenjdk.jitwatch.ui.sandbox.SandboxStage.access$1000(SandboxStage.java:73)
	at org.adoptopenjdk.jitwatch.ui.sandbox.SandboxStage$11.run(SandboxStage.java:394)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.adoptopenjdk.jitwatch.report.suggestion.SuggestionWalker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

**Comment by paplorinc** [comment]
The only non-gradle solution I know is running `mvn -DskipTests=true clean install` before `mvn exec:java`, i.e. deploying locally, so that the `ui` subproject finds the needed dependencies.

**Comment by allandequeiroz** [comment]
Isn't a option include ```<phase>compile</phase>``` and start it when we do ```mvn clean compile```?

**Comment by chriswhocodes** [comment]
#wontfix Got better things to do than fight with maven :(
