### ISSUE TITLE
JarScan significantly slower now it uses ProcessBuilder around javap instead of JavapTask

### ISSUE THREAD

**Issue by chriswhocodes** [AdoptOpenJDK/jitwatch#254]
visualvm confirms nearly 100% of time spent in org.adoptopenjdk.jitwatch.process.AbstractProcess which calls the ProcessBuilder so either my usage of it is badly wrong or invoking the external javap process repeatedly is far slower than using JavapTask (which I removed as it's not supported in JDK9).

Will investigate further and update issue with timings.

**Comment by chriswhocodes** [comment]
Just realised that javap tool can accept a list of classnames and processes them all to the same output.

Might be possible to scan the jar zip entries for all class names and then pass them all or in batches to javap. Could then split the output back to per-class and multithread the bytecode parsing.

Alternatively investigate use of ByteBuddy as the class file parser for JITWatch. Need it to be able to output same disassembled bytecode as javap -v -p

**Comment by weixingsun** [comment]
@chriswhocodes any recommendation to fix it ?

**Comment by chriswhocodes** [comment]
One possible solution is to pass multiple class names to the javap process and then split the output before parsing.

You could batch them up in the loop that reads the zip entries. This would eliminate the overhead of the process builder.

Feel free to submit a pull request if you like or else I'll try and get round to adding this.

Cheers

Chris

**Comment by chriswhocodes** [comment]
Idea: Use reflection to invoke JavapTask where it is available (pre 9 JDK). If not then fallback to slower ProcessBuilder wrapper (and batch this to improve perf).

**Comment by chriswhocodes** [comment]
Fixed with https://github.com/AdoptOpenJDK/jitwatch/commit/1365bf528b55e487166363708b21103588a3dcac

Detects if com.sun.tools.javap.JavapTask is available via reflection and uses if present.

If JavapTask not available then it will fall back to a ProcessBuilder around java/bin/javap which is fine for loading bytecode of single class but unusably slow when using JarScan tool on large jars containing 1000s of methods.

**Comment by chriswhocodes** [comment]
NB com.sun.tools.javap.JavapTask is still present in JDK9 release candidate (although prints warnings about illegal access).
