### ISSUE TITLE
JITWatch unable to locate generated assembly code

### ISSUE THREAD

**Issue by lukeg** [AdoptOpenJDK/jitwatch#256]
JITWatch does not seem to see my assembly code and prints the following message in its windows: 

> Assembly not found. Was -XX:+PrintAssembly option used?

I am using Oracle's JRE 1.8.0_121 on Windows 10 Home. I've added dissasembly dlls to my JRE. The dlls were downloaded from FCML project. I can confirm that assembly is generated when I run program with` java -XX:+UnlockDiagnosticVMOptions  -XX:+PrintAssembly test.Test` options.

I've configured JITWatch paths so that *.java and *.class files are visible to it. For JITWatch analysis I run my Java program with` java -XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:+PrintAssembly test.Test` and open the generated .log file with JITWatch. It can see the Java code and bytecode, but not the assembly.

When opening a method for inspection in JITWatch, the following error appears on a console:

> 21:29:30.098 [Thread-4] ERROR o.a.j.m.a.AssemblyProcessor - Could not determine architecture from '[Disassembling for mach='amd64']'

The source code and inspected log files are available [here](https://gist.github.com/lukeg/96f791ece90f329eef7b65982776f992).

**Comment by chriswhocodes** [comment]
Fixed by https://github.com/AdoptOpenJDK/jitwatch/commit/889c2464bf4c016ed1d9d1209f389f47381a99a3

Thanks for reporting.
