### ISSUE TITLE
Not JIT-compiled

### ISSUE THREAD

**Issue by carymrobbins** [AdoptOpenJDK/jitwatch#262]
After compiling the following Scala 2.10 source -

```scala
object Example {

  final class OptionOps[A](val repr: Option[A]) extends AnyVal {
    def contains(a: A): Boolean = repr.isDefined && repr.get == a
  }

  implicit def toOptionOps[A](x: Option[A]): OptionOps[A] = new OptionOps(x)

  def main(args: Array[String]): Unit = {
    if (Option(1).contains(1)) println("got em") else println("nap")
  }
}
```

Then running with the following JVM options (tried with both IntelliJ and SBT) -

```
-XX:+UnlockDiagnosticVMOptions
-XX:+TraceClassLoading
-XX:+LogCompilation
-XX:+PrintAssembly
```

I can see the assembly output in the console and in the generated hotspot file. However, when opening the log in jitwatch, configuring the source file in **Source locations** and the classes dir and scala-library jar in **Class locations**, upon choosing TriView I can see the source file and bytecode but cannot see the assembly.

![image](https://user-images.githubusercontent.com/3103764/28793220-f2e00fb2-75f7-11e7-9f9a-08e1fcd673ab.png)

**Comment by chriswhocodes** [comment]
Hi Cary,

I'm not familiar with Scala but does that code run for long enough to invoke the JIT compiler?

If you're using JDK8 you'll need to make sure methods are invoked a couple of thousand times to trigger a C1 (client) compilation and around 10,000 times to trigger the C2 (server) compiler and unlock the advanced optimisations.

If it does then have you built hsdis (the HotSpot disassembly binary) and added it to your JRE? Instructions for building and installing hsdis can be found here: https://github.com/AdoptOpenJDK/jitwatch/wiki/Building-hsdis

Cheers,

Chris

**Comment by carymrobbins** [comment]
Ahhh I just need to make sure it gets invoked enough times. Thanks @chriswhocodes!  Seems to work now.

```scala
object Example {

  final class OptionOps[A](val repr: Option[A]) extends AnyVal {
    def optHasValue(a: A): Boolean = repr.isDefined && repr.get == a
  }

  implicit def toOptionOps[A](x: Option[A]): OptionOps[A] = new OptionOps(x)

  def main(args: Array[String]): Unit = {
    for (x <- (1 to 200)) {
      for (y <- (1 to 200)) {
        val opt = Option(x)
        if (example(opt, y)) println("got em") else println("nap")
      }
    }
  }

  private def example(opt: Option[Int], i: Int): Boolean = opt.optHasValue(i)
}
```

**Comment by XuDongZe** [comment]
thanks

> Hi Cary,
> 
> I'm not familiar with Scala but does that code run for long enough to invoke the JIT compiler?
> 
> If you're using JDK8 you'll need to make sure methods are invoked a couple of thousand times to trigger a C1 (client) compilation and around 10,000 times to trigger the C2 (server) compiler and unlock the advanced optimisations.
> 
> If it does then have you built hsdis (the HotSpot disassembly binary) and added it to your JRE? Instructions for building and installing hsdis can be found here: https://github.com/AdoptOpenJDK/jitwatch/wiki/Building-hsdis
> 
> Cheers,
> 
> Chris

wa oh, it's work. thanks very much.
