### ISSUE TITLE
Support of plain folders in JarScan tool

### ISSUE THREAD

**Issue by mrserb** [AdoptOpenJDK/jitwatch#264]
It will be useful if the jarscan tool will support plain folders which contain a number of classfiles.

**Comment by chriswhocodes** [comment]
Done : ) https://github.com/AdoptOpenJDK/jitwatch/commit/60a7815eb8cbb283577495fe02d52ae8d660cd2b
JarScan can now accept class folders as well as jars for input:
`./jarScan.sh --mode=maxMethodSize --limit=325 core/target/classes/`

**Comment by mrserb** [comment]
Thank you!
