### ISSUE TITLE
InlineSize labels are mixed up Sandbox Configuration

### ISSUE THREAD

**Issue by vyazelenko** [AdoptOpenJDK/jitwatch#266]
The labels for inlineSizes are the other way around:
![wrong_labels](https://user-images.githubusercontent.com/696855/31407832-a5b68238-ae06-11e7-8743-56fe525be95d.png)

If I run ```java -XX:+PrintFlagsFinal``` I get the following values on JDK 8:
```
     intx MaxInlineLevel                            = 9                                   {product}
     intx MaxInlineSize                             = 35                                  {product}
...
     intx FreqInlineSize                            = 325                                 {pd product}
```
Which hints that either the labels are wrong or the default values for these labels are mixed up.

**Comment by chriswhocodes** [comment]
Oh the shame!
Fixed with https://github.com/AdoptOpenJDK/jitwatch/commit/ad3c2b3db60b485bc76ca238136f76d44dfa07fb
Thanks for the report!
Luckily those values were only used if set different to the defaults.
