### ISSUE TITLE
No sources are shown in TriView when navigating from the "Eliminated Allocation Report" 

### ISSUE THREAD

**Issue by vyazelenko** [AdoptOpenJDK/jitwatch#270]
If I open  "Eliminated Allocation Report" and then click on "View BCI XX" then I get a TriView without sources:
![triview-no-sources](https://user-images.githubusercontent.com/696855/31584494-e01752a2-b1af-11e7-85f1-e917e24b015b.png)
However if I navigate to the same method from the main screen the TriView is correct:
![triview-snapshot-2017 10 15 13 52 47](https://user-images.githubusercontent.com/696855/31584514-2c343c40-b1b0-11e7-8cc4-d01a1def8092.png)

**Comment by vyazelenko** [comment]
Similar thing happens if I just select a class on the Packages view and click on "TriView" button:
![triview-snapshot-2017 10 15 13 54 13](https://user-images.githubusercontent.com/696855/31584531-6fb5d4c4-b1b0-11e7-8d24-7b8de7b9c9a6.png)

**Comment by chriswhocodes** [comment]
Sounds like I broke this when I refactored the focusing :(
Added to my TODO.

**Comment by chriswhocodes** [comment]
Fixed in https://github.com/AdoptOpenJDK/jitwatch/commit/f7c372b88eadf13f14cb29558cfe80a0ed54b0ab

Please confirm and close issue if you agree?

Thanks,

Chris

**Comment by chriswhocodes** [comment]
Pretty sure I've got them all now (and changed the TriView interface to ensure refresh of source pane).
Closing issue, please reopen if needed.
Thanks Dmitry!
