### ISSUE TITLE
JITwatch- to get assemblycode

### ISSUE THREAD

**Issue by Rids123** [AdoptOpenJDK/jitwatch#272]
I want to generate assembly code for the java file for a simple "hello world" java code.
But JITwatch is showing error  "Not JIT compiled" code.
Please help me to solve this issue.
![1](https://user-images.githubusercontent.com/33311898/32315596-a9cb97a0-bfa4-11e7-8331-1a926ad58a32.png)
![2](https://user-images.githubusercontent.com/33311898/32315616-be7e11c8-bfa4-11e7-8d72-c52fecbc2399.png)

**Comment by chriswhocodes** [comment]
Hi, unless you use -Xcomp then HotSpot will only compile methods that are invoked a large number of times.
