### ISSUE TITLE
Must run ant clean before being able to build

### ISSUE THREAD

**Issue by malinkallen** [AdoptOpenJDK/jitwatch#274]
After having downloaded jitwatch, I ran
`ant jar`
which gave the following error:
```
BUILD FAILED
/home/malin/bin/jitwatch/build.xml:15: The following error occurred while executing this line:
/home/malin/bin/jitwatch/ui/build.xml:47: /home/malin/bin/jitwatch/ui/src/test/java does not exist.
```
Indeed, the directory ui/src/test/java didn't exist. However, when I ran
`ant clean`
it was created and I was able to build the jar.

I notice that there is no test code for ui (at least not in ui/src/test). Is building test classes (line 41-49 in ui/build.xml) really necessary? If so, wouldn't it be better to create `test_src` on line 41?

**Comment by chriswhocodes** [comment]
Fixed by making compile depend on clean. Can't believe this was missing!
Thanks for the report.
