### ISSUE TITLE
How to get JITWatch sandbox to use a particular JDK

### ISSUE THREAD

**Issue by chrisseaton** [AdoptOpenJDK/jitwatch#275]
Like many people I've got several JDKs installed on my system. I switch between them using `jenv`. Everything looks like it's going to use `labsjdk1.8.0_151-jvmci-0.39`:

```
Chriss-MacBook-Pro:jitwatch chrisseaton$ echo $JAVA_HOME
/Users/chrisseaton/Documents/labsjdk1.8.0_151-jvmci-0.39/Contents/Home
Chriss-MacBook-Pro:jitwatch chrisseaton$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b01-internal-jvmci-0.39, mixed mode)
Chriss-MacBook-Pro:jitwatch chrisseaton$ javac -version
javac 1.8.0_151
Chriss-MacBook-Pro:jitwatch chrisseaton$ mvn -version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T08:58:13+01:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Users/chrisseaton/Documents/labsjdk1.8.0_151-jvmci-0.39/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.2", arch: "x86_64", family: "Mac"
```

UI shows `VM is Oracle Corporation labsjdk1.8.0_151`.

But when I run JITWatch with `mvn clean compile test exec:java`, the sandbox still somehow runs another JDK installed on my system.

```
Running: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/javac -g -d /Users/chrisseaton/Documents/jitwatch/sandbox/classes -cp /Users/chrisseaton/Documents/jitwatch/sandbox/classes /Users/chrisseaton/Documents/jitwatch/sandbox/sources/SafePointTest.java 
```

How does the JITWatch Sandbox find the JDK, and how can I tell it to just use the one it's running with?

**Comment by chriswhocodes** [comment]
Hi Chris,

The "Configure Sandbox" button presents you with a config dialog with 2 rows of buttons where you can configure the path to the runtime for each supported JVM language (Java, Scala, etc.)
<img width="1031" alt="screen shot 2018-01-06 at 16 37 15" src="https://user-images.githubusercontent.com/1898314/34641701-0d3f17d8-f300-11e7-8c9c-dc95a3cd664a.png">

I think since JDK 9 it makes sense to support more than 1 execution profile per language to make it easier to switch between them. Will add that to my TODO list.

On another note, I'd really like to get 1st class support for Graal into JITWatch this year. Happy to do a Skype etc to chat about how to make that happen.

Cheers,

Chris

**Comment by chriswhocodes** [comment]
Also, the first time the sandbox starts, it populates the Sandbox Java executable path with the runtime JVM at the time.

**Comment by chrisseaton** [comment]
> The "Configure Sandbox" button presents you with a config dialog with 2 rows of buttons where you can configure the path to the runtime for each supported JVM language (Java, Scala, etc.)

Thanks I didn't look there as I thought it was a JVM thing, so wasn't Java specific, but I see it now. By the way when I try to browse to find a JDK the file selector pops up underneath and stays underneath the dialog, so you can't use it. See the focus on the button and window but it's underneath everything. Probably a Swing bug rather than yours.

![](https://i.imgur.com/G5F25SY.jpg)

> Also, the first time the sandbox starts, it populates the Sandbox Java executable path with the runtime JVM at the time.

Ah this was my problem - why do you want to cache this? I think for me it'd make sense to always run the current JDK, not the one that JITWatch happened to be used with one time I ran it in the past.

> On another note, I'd really like to get 1st class support for Graal into JITWatch this year.

Yes I've suggested someone take a look at the issue talking about this.

**Comment by chriswhocodes** [comment]
> Ah this was my problem - why do you want to cache this? I think for me it'd make sense to always run the current JDK, not the one that JITWatch happened to be used with one time I ran it in the past.

I think you're right, I get caught by that each time I swap machines. I will make the Sandbox use the runtime JVM unless the user overrides that in the config.

**Comment by chriswhocodes** [comment]
Hi Chris,
As of https://github.com/AdoptOpenJDK/jitwatch/commit/9ac7454636049ba86315a2ee06368f1d199ba49d JITWatch does not cache the first JVM it sees as the Sandbox JVM. If no JDK is set in the Sandbox config then it will use the currently running JDK. Tested with 7,8,9. In the future I plan to add profile support so switching JVMs will not require restarting JITWatch.
Cheers,
Chris
