### ISSUE TITLE
Graal support in JITWatch

### ISSUE THREAD

**Issue by chriswhocodes** [AdoptOpenJDK/jitwatch#276]
This is a new ticket for discussing making JITWatch compatible with the JIT compiler logs from the Graal VM. It replaces https://github.com/AdoptOpenJDK/jitwatch/issues/265.

Here is the current set of resources I'm planning to use. Please feel free to add any other useful resources to this issue.

http://chrisseaton.com/rubytruffle/jokerconf17/
http://openjdk.java.net/jeps/243
https://github.com/oracle/graal
https://github.com/graalvm/graal-core/blob/master/docs/Debugging.md

**Comment by chriswhocodes** [comment]
Hacking on this at JCrete.
This command line
`grep "debug\.scope" * -R | grep -v "/test/" | grep -o '".*"' | cut -d'"' -f2|sort -u`
Identifies the following list of (non-testing) debug scopes that contain the different topics that Graal categorises logging under.
```
AfterLifetimeAnalysis
AllocateTraces
Allocating Trace%d: %s (%s)
AOTCompileMethod
AOTParseMethod
ArrayCloneSnippet
BackEnd
BottomUpAllocator
BuildConstantTree
BuildDefUseTree
buildInitialGraph
BuildSnippetGraph
CheckUninterruptibleAllocations
CheckUninterruptibleCallees
CheckUninterruptibleCallers
CheckUninterruptibleOverrides
CLOmodify
ClosedWorldAnalysis
CodeGen
CodeInstall
CompileStubs
Compiling
CompilingStub
ConstantTreeAnalyzer
ControlFlowGraph
CreateBootImage
createGraph
CreateGraph
doInline
DumpTraceStatistics
EffectsPhaseWithSchedule
EmitLIR
Field offset computation
FrontEnd
GetIntrinsicGraph
GraalCompiler
GraphDecoder
GraphEncoder
GraphState
InlineGraph
InlineTrivial
Inlining
InstallingTruffleStub
InterTraceHints
IntrinsifyMethodHandles
InvokeCC
IrreducibleLoops
iteration 
KillCFG
LIRStages
LivenessAnalysis
LoweringSnippetTemplate
LSRAOptimization
MatchComplexExpressions
MustNotSynchronizeAnnotationChecker
NativeBootImage.build
NodeCosts
NodeCostSummary
Operation
Parsing
peeling
ReassociateInvariants
RegisterLowerings
RegisterVerifier
Remove Phi In
RestrictHeapAccessAnnotationChecker
RuntimeCompile
RuntimeOptimize
SnippetSpecialization
SnippetStub
SpecializeSnippet
SSAVerifier
StackSlotAllocationBuildIntervals
StackSlotMappingLIR
StubCompilation
Truffle
TruffleCompilation
TruffleFinal
TruffleGraal.GraalCompiler
TrufflePartialEscape
TrufflePerformanceWarnings
TruffleTree
Verify GlobalLivenessInfo
WithGraphChangeMonitoring
```

**Comment by franok** [comment]
**bump **: I got JIT compiler logs from GraalVM running in JITWatch.

_Note1:_
Not sure if anyone else tried this recently or if any work has been done on JITWatch side, but the last bit of information I could find on this was [this comment](https://github.com/AdoptOpenJDK/jitwatch/issues/265#issuecomment-356608658) in #265.

_Note 2:_
Is this issue about Graal compatibility in general? Or only about displaying assembly code? If second, and using JITWatch with Graal compiler logs worked all the time, I suggest to rename this issue accordingly to avoid confusion. Then, the following would be pointless. If not, here's what I did:

After reading through the old issue and finding that this follow-up issue #276 is open for almost two years, I was curious to simply try out if maybe GraalVM would (meanwhile) output compiler logs in a way that JITWatch would understand.

#### generated compiler log (within a jmh benchmark):
```
~/jvm-evaluation/graalvm-ce-java11-20.2.0/bin/java -XX:+HeapDumpOnOutOfMemoryError -jar target/benchmarks.jar Backtracking -jvmArgs "-Xms5g -Xmx5g -XX:+HeapDumpOnOutOfMemoryError -XX:+UnlockExperimentalVMOptions -Dlibgraal.MaxNewSize=6442450944 -Dlibgraal.PrintGC=true -XX:+AlwaysPreTouch -XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:+PrintAssembly -XX:LogFile=jitwatch-backtracking-sudoku_graalvm.log" -rf json -rff jmh-result-graalvm-backtracking-sudoku.json -i 21000 -f 1 -to 360m | tee output-graalvm-backtracking-sudoku-$(date +'%FT%H-%M').log
```

relevant options to generate the compiler log were:
```
-XX:+UnlockDiagnosticVMOptions 
-XX:+TraceClassLoading 
-XX:+LogCompilation 
-XX:+PrintAssembly 
-XX:LogFile=jitwatch-backtracking-sudoku_graalvm.log
```

output was this compiler log: [jitwatch-backtracking-sudoku_graalvm.log](https://github.com/AdoptOpenJDK/jitwatch/files/5471867/jitwatch-backtracking-sudoku_graalvm.log)

#### loaded it into JITWatch, selected Parser: HOTSPOT

![image](https://user-images.githubusercontent.com/17296805/97816831-7c3e5a80-1c98-11eb-8b2b-2131085c7d0e.png)


note: Assembly View not working (expected/known issue)

**Comment by chriswhocodes** [comment]
Thanks for reporting @franok :)
I'm finding a little more time for JITWatch now so will definitely look at how it can better support GraalVM.
