### ISSUE TITLE
Please update the instruction to build hsdis

### ISSUE THREAD

**Issue by stephanrauh** [AdoptOpenJDK/jitwatch#278]
@chriswhocodes  Your instructions (https://www.chrisnewland.com/building-hsdis-amd64dylib-on-mac-osx-376) on how to build hsdis on OSX are broken. Actually, there are two issues:

First, the URL in the first line of the instructions ceased to exist.

After a while, I found this archive which seems to contain the required files: http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/tags

However, when I try to compile hsdis, I always get an compiler error:
```
/Users/stephan/git/temp/hotspot-a769f683df5d/src/share/tools/hsdis/binutils-2.24/bfd/mach-o.c:2211:20: error: shifting a negative signed value
      is undefined [-Werror,-Wshift-negative-value]
  mdata->filelen = FILE_ALIGN(mdata->filelen, 2);
```

Is there a compiler setting I have missed?

I'm running a current OS X with High Sierra 10.13.3.

**Comment by chriswhocodes** [comment]
Looks like you need binutils 2.28 for latest hsdis.

https://github.com/AdoptOpenJDK/jitwatch/wiki/Building-hsdis
https://www.chrisnewland.com/updated-instructions-for-building-hsdis-on-osx-417

**Comment by stephanrauh** [comment]
Thanks for your quick and helpful response!
