### ISSUE TITLE
Total JIT Time in statistics does not match Longest Compilation Times

### ISSUE THREAD

**Issue by jocull** [AdoptOpenJDK/jitwatch#289]
Sorry if this is a duplicate! I noticed these two values do not match. I added some [extra code here to sum the difference reported in Longest Compilation Times](https://github.com/jocull/jitwatch/commit/237ed56e516ca4a189465312cf2b8fa4918eab88) (dirty hacks, sorry!) just for my own information. I'm not exactly sure what the issue in the stats code is, but it appears all compilation times return zero. Perhaps an issue in the visitor?

**Comment by chriswhocodes** [comment]
Thanks for reporting, will investigate!

**Comment by chriswhocodes** [comment]
![toplist_slowest_compile_times](https://user-images.githubusercontent.com/1898314/44878072-d3ea7100-ac9d-11e8-8b33-b666c4653056.png)
Hi, this toplist seems to be working for me. Would you mind sharing the log file and letting me know which JDK you used to generate it?
Thanks.

**Comment by jocull** [comment]
Oh yes, that one is just fine! This is the one I was trying to refer to:

![image](https://user-images.githubusercontent.com/246455/44878245-5a8a5880-ac74-11e8-90a8-a478edc08206.png)

Where it says "Total JIT Time*"

**Comment by chriswhocodes** [comment]
![stats](https://user-images.githubusercontent.com/1898314/44878398-b073f600-ac9e-11e8-996f-68d7a944cea0.png)
OK, I'm getting a zero for that field too. Looks like a bug.

**Comment by jocull** [comment]
Thank you! Glad you were able to find it quickly :smile:
