### ISSUE TITLE
Assembly viewer - inlined ASM missing?

### ISSUE THREAD

**Issue by toaler** [AdoptOpenJDK/jitwatch#290]
I've been using JITWatch to understand how to discover JIT opportunties and so far it's been a great tool.  My question pertains to the assembly view and inlined ASM.  

I have a method testBigMethod that calls bigMethod.  Using FreqInlineSize I was able to get bigMethod inlined into the caller testBigMethod.  

Using JitWatch confirms this via the call chain view as well as the bytecode view invokespecial high lighted as green.  So i'm 100% sure the inlining of bigMethod in testBigMethod is occuring.

Naively, I was expecting the asm for bigMethod to show up in the assembly view, but to my surprise I can't see it nor any obvious reasons as to why it's not there.  Is this by design?  I'm looking for details as why it's not there.  Screenshot of what i'm seeing below.

![screen shot 2018-09-11 at 9 57 08 pm](https://user-images.githubusercontent.com/1082867/45403285-6e3ba480-b60e-11e8-830b-d99ce2f98160.png)

Thanks in advance,
- Brian

**Comment by chriswhocodes** [comment]
Hi Brian,
I see you're using JMH which processes the benchmarking annotations to produce the final bytecode that includes the test loops etc.
I see from the screenshot that the class and method names don't appear to be mangled (I think JMH produces synthetic method names).
Is there any chance you could send me the source / hotspot log file and I'll investigate?
Thanks,
Chris

**Comment by toaler** [comment]
I think JMH generates various classes that eventually call down to bench.jit.InliningTest.testBigMethod  to avoid DCE and other jit optimizations from happening.  Here's what you asked for.

[InliningTest.java.zip](https://github.com/AdoptOpenJDK/jitwatch/files/2376980/InliningTest.java.zip)


[hotspot_pid94018.log.zip](https://github.com/AdoptOpenJDK/jitwatch/files/2376979/hotspot_pid94018.log.zip)

**Comment by toaler** [comment]
@chriswhocodes let me know if you need anything else.  I can see that bench.jit.InlingTest.bigMethod is being inlined (call chain and bytecode pane of triview are green) into bench.jit.InliningTest.testBigMethod.  I just don't get why I don't see the ASM for bigMethod inlined in testBigMethod assembly.

**Comment by shipilev** [comment]
@toaler I think you need to say: 
```
  public long testBigMethod() {
    return bigMethod(1, 1);
  }
```
to _actually_ avoid DCE. Stands to reason there is no generated code for the method otherwise -- it was optimized away.

**Comment by chriswhocodes** [comment]
Hi Brian,
I've run your test class and I get the same result:
![jitwatch-snapshot-2018 09 19 22 38 45](https://user-images.githubusercontent.com/1898314/45783188-006e2900-bc5d-11e8-8bed-38957eeade01.png) with TriView: 
![triview-snapshot-2018 09 19 22 38 53](https://user-images.githubusercontent.com/1898314/45783212-0cf28180-bc5d-11e8-9cc4-4b88a3a3c1fe.png) where you can see no inlining.
I thought this might be because the inlined method body had been eliminated due to DCE because the result of bigMethod() is not used.

**Comment by chriswhocodes** [comment]
When I change your code I get this
![triview-snapshot-2018 09 19 22 51 46](https://user-images.githubusercontent.com/1898314/45783912-0e24ae00-bc5f-11e8-801e-0963679bc688.png)
If you look at the line 
`mov $0xe, eax`
 you will see the result of your calculations (return 14) so the compiler has done a good job of reducing your method to a constant return of 14 (0xe in hex).
Hope this helps?
