### ISSUE TITLE
JVM Crash after running jlinked binary

### ISSUE THREAD

**Issue by KrishnaST** [AdoptOpenJDK/jitwatch#301]
[hs_err_pid1548.log](https://github.com/AdoptOpenJDK/jitwatch/files/2956845/hs_err_pid1548.log)
[hs_err_pid5904.log](https://github.com/AdoptOpenJDK/jitwatch/files/2956846/hs_err_pid5904.log)
[hs_err_pid15068.log](https://github.com/AdoptOpenJDK/jitwatch/files/2956847/hs_err_pid15068.log)

[telnetclient.zip](https://github.com/AdoptOpenJDK/jitwatch/files/2956851/telnetclient.zip)

**Comment by chriswhocodes** [comment]
Hi, I don't think this is related to JITWatch.

Did you mean to report it to https://github.com/AdoptOpenJDK/openjdk-build ?

/cc @karianna
