### ISSUE TITLE
Tags, binaries and GitHub release notes for future releases?

### ISSUE THREAD

**Issue by retronym** [AdoptOpenJDK/jitwatch#306]
I've created a homebrew [formula](https://github.com/retronym/homebrew-formulas/blob/master/jitwatch.rb) that builds and installs jitwatch on Mac.

```
$ brew install retronym/formulas/jitwatch
$ jitwatch-headless -help
Usage: LaunchHeadless <options> <hotspot log file>
options:
-e	Show parse errors
-m	Show model
-c	Show only compiled methods in model (use with -m)
-s	Show code suggestions
-t	Show compilation timeline
-f	Write output to headless.csv
-i	Show inline failed calls
$ jitwatch
```

It's a bit of a hack because:
  - it needs to build from source
  - there aren't recent tags to refer to in this repository.

Would you consider using:
  - using tags for future releases?
  - including the "publish to maven central" step again in the release process (I think this was done for a few releases but hasn't been done recently)
  - maybe, use maven-assembly-plugin or the like to create a zip release to add to the assets of the [Github releases](https://github.com/AdoptOpenJDK/jitwatch/releases).

**Comment by chriswhocodes** [comment]
Hi Jason,
I can definitely start using git tags.
I tried publishing to maven central a couple of times and it was almost enough to make me want to give up computing and become a potato farmer ;)
I'll take a look into your 3rd suggestion too.
Cheers,
Chris

**Comment by chriswhocodes** [comment]
Hi Jason, I've made the first binary release of JITWatch here: https://github.com/AdoptOpenJDK/jitwatch/releases/tag/1.4.0

I'll look into creating a maven central release from this shortly.

**Comment by retronym** [comment]
Thanks! That's allowed me to [simplify](https://github.com/retronym/homebrew-formulas/pull/2) my homebrew formula for MacOS installation greatly!
