### ISSUE TITLE
TestParseUtil#testRegressionJavaUtilPropertiesLoadConvert fails on JDK 13

### ISSUE THREAD

**Issue by ggam** [AdoptOpenJDK/jitwatch#312]
`TestParseUtil#testRegressionJavaUtilPropertiesLoadConvert()` test checks for the existentence of the private `Properties#loadConvert(char[], int, int, char[])` which is indeed not present at least on Java 13, where is was replaced by `Properties#loadConvert(char[], int, int, StringBuilder)`.

I haven't found any use of that private method on the rest of the code. Does it specifically test that method for some reason or can it be changed to any public one to verify its signature?

**Comment by chriswhocodes** [comment]
Hi @ggam thanks for reporting.
I can't remember why I picked this method for testing the parser but I think it was a mistake to rely on core library methods and I will rewrite the test to use a method in the JITWatch package hierarchy.
I'll close the issue once I've fixed this.
Cheers,
Chris

**Comment by chriswhocodes** [comment]
Fixed in https://github.com/AdoptOpenJDK/jitwatch/commit/5628357dbd6af1be0145edbc7fd5ef2d137d1551.
