### ISSUE TITLE
Outdated Binaries

### ISSUE THREAD

**Issue by deaddowney** [AdoptOpenJDK/jitwatch#324]
I'm trying to use Jitwatch against a Java 11 application and am running into the -XX:+TraceClassLoading issue that others have reported.  Turns out I was using an old version of Jitwatch (1.0.0) that was referred to by the wiki.  I went to mvn central and found the latest there was jitwatch-ui:1.1.5 from 2018.  I've run that and still see the same issue.  I've tried to download the latest build from CI as mentioned on the wiki but get a 521 error code for http://chriswhocodes.com:8080/

I am currently firewalled off from getting the source and building myself.  Is there an alternative place to get the current build that works with Java 11?

**Comment by chriswhocodes** [comment]
Hi,
I discontinued my Jenkins CI a long time ago as it's a security nightmare.
The maven artifacts are also out of date because I don't need that maven central pain in my life!
I'll see if I can produce a shaded jar containing the (few) libs it uses and upload that to chriswhocodes.com

**Comment by deaddowney** [comment]
Thanks Chris!  Just out of curiosity, have you tried a Mvn central alternative, like BinTray or used the Releases feature in Github to host the binaries?

**Comment by chriswhocodes** [comment]
I think GitHub releases makes sense. It's a desktop app (for most people) not a library so maven central isn't really the right place imo.

Do you need a build that contains JavaFX libs?

**Comment by deaddowney** [comment]
No, I have the JavaFX libs.  Just the equivalent to whatever was in Mvn Central should be fine.

**Comment by chriswhocodes** [comment]
Let me know if this works for you? https://chriswhocodes.com/jitwatch-ui-shaded.jar

It contains JavaFX until I work out how to make a build without it.

**Comment by deaddowney** [comment]
@chriswhocodes Awesome job!  Works now!  Thank you!!

**Comment by chriswhocodes** [comment]
Cool, glad it worked. I'll clean up the wiki and make a page on my blog for binaries.
