### ISSUE TITLE
JITWatch is ignoring LD_LIBRARY_PATH on Linux when searching for hsdis

### ISSUE THREAD

**Issue by Tech-Risk-Chris** [AdoptOpenJDK/jitwatch#327]
Not all developers have sudo access to their java installation to copy the shared library for HSDIS there.

OpenJDK recommends using LD_LIBRARY_PATH to help Java find the hsdis shared library anyway, which works like a charm for -XX:+PrintAssembly and similar.

JITWatch does not look there for HSDIS though.

I have a patch proposal (see attached txt file), but I cannot quite get your formatting right, otherwise this would be a pull request :)

[jitWatch-patch-20200901-1227.patch.txt](https://github.com/AdoptOpenJDK/jitwatch/files/5155605/jitWatch-patch-20200901-1227.patch.txt)

**Comment by chriswhocodes** [comment]
Thanks! Added your patch in https://github.com/AdoptOpenJDK/jitwatch/commit/567b85bb77ef8a880f84e8d124f9d6ccafcafc14
