### ISSUE TITLE
headless mode export nothing to csv

### ISSUE THREAD

**Issue by leonchen83** [AdoptOpenJDK/jitwatch#329]
java version : 
```
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment 20.7-(Zulu-11.41+23-linux_x64)-Microsoft-Azure-restricted (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM 20.7-(Zulu-11.41+23-linux_x64)-Microsoft-Azure-restricted (build 11.0.8+10-LTS, mixed mode)
```
jitwatch version:
```
        <dependency>
            <groupId>com.chrisnewland</groupId>
            <artifactId>jitwatch</artifactId>
            <version>1.1.5</version>
        </dependency>
```

jit log
[hotspot_pid18196.zip](https://github.com/AdoptOpenJDK/jitwatch/files/5358412/hotspot_pid18196.zip)

headless.csv

```
[12:47:55 chenby@balrog-dev jitwatch]$ cat headless.csv 
sep=|
[12:47:58 chenby@balrog-dev jitwatch]$ 
```

**Comment by chriswhocodes** [comment]
Thanks for reporting. I will investigate.

**Comment by chriswhocodes** [comment]
Hi @leonchen83 please clone the latest version of JITWatch and build it using mvn clean package

The version 1.1.5 in maven central is very out of date and missing a lot of bug fixes. I will try to update the version in maven central soon.

Thanks,

Chris
