### ISSUE TITLE
I restarted a thread in the main method, what should I do to see the machine code in the thread

### ISSUE THREAD

**Issue by guangmingdexin** [AdoptOpenJDK/jitwatch#334]
private static boolean run = true;

    public static void main(String[] args) {

        Thread t = new Thread(() -> {
            int a = 5;
            while (run) {
                a = 1;
            }
            System.out.println("forever here！");
        });
        t.start();
        Sleep.sleep(1);
        run = false; 
    }

**Comment by chriswhocodes** [comment]
Hi @guangmingdexin are you sure this code runs for long enough to trigger JIT compilation?

If you run it in the JITWatch sandbox mode then you will see a file called sandbox.log generated which contains all the JIT compiler decisions. You can paste that here if you like.

Cheers,

Chris

**Comment by guangmingdexin** [comment]
Thanks, I will test.
