### ISSUE TITLE
TraceClassLoading is Expired in JDK17

### ISSUE THREAD

**Issue by chriswhocodes** [AdoptOpenJDK/jitwatch#336]
https://chriswhocodes.com/hotspot_options_openjdk8.html?s=TraceClassLoading

TraceClassLoading is used in the JITWatch Sandbox. Option is "Expired" in JDK17 so the JVM fails to start when the Sandbox runs with this option.

Options:
detect `java` version and remove switch from runtime options as appropriate
Remove reliance on TraceClassLoading (including producing skeleton MetaClass objects from LogCompilation signatures only

**Comment by chriswhocodes** [comment]
Fixed in https://github.com/AdoptOpenJDK/jitwatch/commit/bcb5ba8f3a8ed6385dd33076c239b785f4be9f5b by removing -XX:+TraceClassLoading - not needed by Sandbox anyway

**Comment by chrisseaton** [comment]
It's still listed in the wiki though?

**Comment by chriswhocodes** [comment]
Thanks for letting me know. The correct fix is for me to support the pre JDK9 `-XX:+TraceClassloading` and also the post JDK9 `-Xlog:class+load=info` if detected.

I'm working on a radical overhaul of the JITWatch classloading which will fix a lot of the annoyances related to switching Java versions :)
