### ISSUE TITLE
Assembly not found while using +PrintAssembly

### ISSUE THREAD

**Issue by awildturtok** [AdoptOpenJDK/jitwatch#338]
I am using the latest jitwatch master, executed with ` mvn clean compile test exec:java` and it isn't showing me any Assembly in the Assembly pane:

![image](https://user-images.githubusercontent.com/1553491/105487279-1cac8580-5cb0-11eb-8c3a-ad10acc52d6d.png)

## Java Version
```
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1-LTS, mixed mode, sharing)
```
## Jitwatch Version
```
$ git describe --tags
1.4.0-6-gbb50980
```

## Comand

```
 java -XX:+UnlockDiagnosticVMOptions -XX:LogFile=mylogfile.log -XX:+PrintAssembly -XX:+LogCompilation -XX:+TraceClassLoading -Xmx120G -XX:+UseG1GC -jar
```

I have observed, that none of the Assembly is logged into mylogfile, but instead to stdout, which is why I've also tried concatenating them but to no avail.

I have attached both stdout and the logfile:

[dumps.zip](https://github.com/AdoptOpenJDK/jitwatch/files/5855556/dumps.zip)

90+% of the relevant source can be built using this Repo: https://github.com/bakdata/conquery/tree/feature/bye-bye-bucket-templates
With `mvn clean package -pl 'backend' -am -DskipTests`

**Comment by andrew-laird-by** [comment]
> I am using the latest jitwatch master, executed with ` mvn clean compile test exec:java` and it isn't showing me any Assembly in the Assembly pane:
> 
> ![image](https://user-images.githubusercontent.com/1553491/105487279-1cac8580-5cb0-11eb-8c3a-ad10acc52d6d.png)
> 
> ## Java Version
> ```
> openjdk version "11.0.9.1" 2020-11-04 LTS
> OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1-LTS)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1-LTS, mixed mode, sharing)
> ```
> 
> ## Jitwatch Version
> ```
> $ git describe --tags
> 1.4.0-6-gbb50980
> ```
> 
> ## Comand
> ```
>  java -XX:+UnlockDiagnosticVMOptions -XX:LogFile=mylogfile.log -XX:+PrintAssembly -XX:+LogCompilation -XX:+TraceClassLoading -Xmx120G -XX:+UseG1GC -jar
> ```
> 
> I have observed, that none of the Assembly is logged into mylogfile, but instead to stdout, which is why I've also tried concatenating them but to no avail.
> 
> I have attached both stdout and the logfile:
> 
> [dumps.zip](https://github.com/AdoptOpenJDK/jitwatch/files/5855556/dumps.zip)
> 
> 90+% of the relevant source can be built using this Repo: https://github.com/bakdata/conquery/tree/feature/bye-bye-bucket-templates
> With `mvn clean package -pl 'backend' -am -DskipTests`

The assembly setup takes extra work, and the steps are different on a Mac vs Windows.  For example, see https://www.chrisnewland.com/updated-instructions-for-building-hsdis-on-osx-417.  

My personal steps in the past were:
hg clone http://hg.openjdk.java.net/jdk/jdk11/

cd jdk11/src/utils/hsdis

wget http://ftp.heanet.ie/mirrors/ftp.gnu.org/gnu/binutils/binutils-2.28.tar.gz

make BINUTILS=binutils-2.28 ARCH=amd64

sudo cp build/macosx-amd64/hsdis-amd64.dylib /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/server/

**Comment by andrew-laird-by** [comment]
FYI I had left a comment on how to enable hsdis, but upon closer reading I see you say that assembly IS being logged to stdout, so nevermind... :-).

**Comment by awildturtok** [comment]
I will check for hsdis anyway, but I am definetly getting something to stdout:

```
ImmutableOopMap{}pc offsets: 308 
ImmutableOopMap{rsi=Oop }pc offsets: 352 Compiled method (c1)  735572 19072       3       jetbrains.exodus.env.TransactionSet::add (156 bytes)
 total in heap  [0x00007f0580cd2390,0x00007f0580cd5790] = 13312
 relocation     [0x00007f0580cd2508,0x00007f0580cd2750] = 584
 main code      [0x00007f0580cd2760,0x00007f0580cd4440] = 7392
 stub code      [0x00007f0580cd4440,0x00007f0580cd44f0] = 176
 oops           [0x00007f0580cd44f0,0x00007f0580cd4528] = 56
 metadata       [0x00007f0580cd4528,0x00007f0580cd4620] = 248
 scopes data    [0x00007f0580cd4620,0x00007f0580cd4dd0] = 1968
 scopes pcs     [0x00007f0580cd4dd0,0x00007f0580cd5720] = 2384
 dependencies   [0x00007f0580cd5720,0x00007f0580cd5730] = 16
 nul chk table  [0x00007f0580cd5730,0x00007f0580cd5790] = 96
```

**Comment by andrew-laird-by** [comment]
Oh, that doesn't quite look like assembly to me.   I actually recently released a blog where I looked at Jitwatch's assembly output so, for convenience, look at https://tech.blueyonder.com/java-giants/ and scroll down a bit to the assembly screenshots.   You should have assembly commands like "mov", "add", "test", etc.   What you showed looks more like the c1 log of what it did rather than true assembly.   So, yes, I am back to thinking your hsdis installation isn't quite right.

**Comment by awildturtok** [comment]
That explains a lot!

**Comment by awildturtok** [comment]
It is working now, thanks for taking the time!
