### ISSUE TITLE
It should download JavaFX components only for the operating system being executed

### ISSUE THREAD

**Issue by tivrfoa** [AdoptOpenJDK/jitwatch#339]
Hi folks,

It downloads all JavaFX components (web, swing, controls, media, ...) for all operating systems.<br>

This is unnecessary, consumes bandwidth and takes longer.

Is it possible to fix this? Thank you!  

```
...
Downloaded from central: https://repo.maven.apache.org/maven2/org/openjfx/javafx-web/15.0.1/javafx-web-15.0.1-mac.jar (30 MB)
Downloaded from central: https://repo.maven.apache.org/maven2/org/openjfx/javafx-web/15.0.1/javafx-web-15.0.1-win.jar (25 MB)
Downloaded from central: https://repo.maven.apache.org/maven2/org/openjfx/javafx-web/15.0.1/javafx-web-15.0.1-linux.jar (34MB)
```

**Comment by chriswhocodes** [comment]
Hi, I'd be happy to accept a PR to fix this. It can probably be done with maven activation profiles?

**Comment by tivrfoa** [comment]
> Hi, I'd be happy to accept a PR to fix this. It can probably be done with maven activation profiles?

I'll try to create a PR for this. Thank you.

**Comment by chriswhocodes** [comment]
Fixed in https://github.com/AdoptOpenJDK/jitwatch/commit/29463ca4b5d97979c86690c36ce8bc1b5aba42ad
