### ISSUE TITLE
Help needed: Assembly not found

### ISSUE THREAD

**Issue by Brixomatic** [AdoptOpenJDK/jitwatch#341]
* Using Windows 10
* Using JDK 15
```console
c:\Program Files\Java\jdk-15.0.1.9-hotspot\bin>java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```
* Downloaded hsdis-1.2.2-win32-amd64.zip (also tried hsdis-1.2.2-win32-x86.zip) from
[https://sourceforge.net/projects/fcml/files/latest/download]()
Copied _hsdis.dll_ and _hsdis.lib_ to
```c:\Program Files\Java\jdk-15.0.1.9-hotspot\bin\server```

* Started jmh benchmark from MINGW64 Terminal like this:
```console
/c/"Program Files"/Java/jdk-15.0.1.9-hotspot/bin/java \
-Xms1g -Xmx1g \
-XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation \
-XX:+DebugNonSafepoints -XX:LogFile=jvm.log \
-jar target/benchmarks.jar 
```

* Started jitwatch using the same JDK:
```console
"c:\Program Files\Java\jdk-15.0.1.9-hotspot\bin\java" -jar jitwatch-ui-1.4.0-shaded-win.jar
```

* Added class files and directories in config, opened log and clicked "start"

* __No assembly found for any method.__ 

Overview:
![no assembly issue](https://user-images.githubusercontent.com/37806303/112997903-d0793800-916d-11eb-9502-4a77f3541654.png)

**Comment by chriswhocodes** [comment]
Hi, I don't see `-XX:+PrintAssembly` in your start command?

**Comment by chriswhocodes** [comment]
Hi, that looks like the disassembler hasn't disassembled the native code back to readable mnemonics.

I've only had success using hsdis from GNU binutils with JITWatch so I'd recommend you try that?

It's fairly easy to build from OpenJDK sources even on Windows:

https://stackoverflow.com/questions/33903276/how-to-build-hsdis-dll-for-windows-32-bit 

https://dropzone.nfshost.com/hsdis/

Cheers,

Chris

**Comment by Brixomatic** [comment]
Following the cygwin-tutorial on dropzone did the trick for me.
Thanks a lot.
