### ISSUE TITLE
VM is null null

### ISSUE THREAD

**Issue by Thihup** [AdoptOpenJDK/jitwatch#352]
Using JDK 11+, the following code in JITWatchUI.java fails to work properly:

https://github.com/AdoptOpenJDK/jitwatch/blob/master/ui/src/main/java/org/adoptopenjdk/jitwatch/ui/main/JITWatchUI.java#L732-L735

A way to fix it would be using some of `java.*` (`java.version`/`java.vendor`) system property

**Comment by chriswhocodes** [comment]
Thanks, I'll take a look at those properties.

**Comment by chriswhocodes** [comment]
Fixed in https://github.com/AdoptOpenJDK/jitwatch/commit/46a8258b8589265500b53d7e70502a7ac53983fd

Thanks for the tip on how to fix this :)
