### ISSUE TITLE
I can't see the assembly instructions.

### ISSUE THREAD

**Issue by GG22G2** [AdoptOpenJDK/jitwatch#355]
When I use jdk8, I can see the correct assembly instructions, but when I use jdk17, Assembly window does not show assembly instructions
![image](https://user-images.githubusercontent.com/31408730/143378792-b214d334-529d-4714-a075-50d611cb8d1c.png)

**Comment by chriswhocodes** [comment]
Hi, are you using the same hsdis for JDK8 and JDK17?

You may need to use a more recently compiled version of hsdis for JDK17. Can you try one from https://builds.shipilev.net/hsdis/ ?

Thanks,

Chris

**Comment by chriswhocodes** [comment]
Hi, I'm closing all the issues except for the ones I'm actively working on.
