### ISSUE TITLE
hsdis download failed on x86 mac

### ISSUE THREAD

**Issue by sureshg** [AdoptOpenJDK/jitwatch#362]
Seems like the URL for the platform-specific dynamic lib is wrong.

```
Sandbox ready. OS is 'Mac OS X' Architecture is 'x86_64'
Disassembler not found
Downloading hsdis from https://chriswhocodes.com/hsdis/hsdis-x86_64.dylib
Download failed
```

**Comment by chriswhocodes** [comment]
Confirmed, will fix!

**Comment by chriswhocodes** [comment]
Fixed in https://github.com/AdoptOpenJDK/jitwatch/commit/eac4d0507b8502bc94bed83833aaa08441be8cea and new release 1.4.6 built to include the fix.

Thanks for reporting!
