### ISSUE TITLE
JITWatch shows garbled characters

### ISSUE THREAD

**Issue by Acorn2** [AdoptOpenJDK/jitwatch#363]
I want to use JITWatch, but the tool buttons are showing garbled characters.

`Mac OS: 10.15.7  and JDK8`

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/23418309/155689173-9226addc-75fb-4a8c-86cd-27fc3668ac0f.png">

**Comment by chriswhocodes** [comment]
Hi, what is the default Locale for your system and what is the language selector setting in the bottom left corner of the main UI?

**Comment by Acorn2** [comment]
the default Locale for your system is chinese,the language of UI  is english.

**Comment by wenwj0** [comment]
I met this issue too.
My system Locale is Chinese, and I select English in the bottom left corner.

**Comment by chriswhocodes** [comment]
Hi, please can you tell me what your default Locale string is?

Thanks,

Chris

**Comment by llCnll** [comment]
i has tested. if system locale is english, it'll ok.
