### ISSUE TITLE
Unable to see source code for project classes as well as java lang classes

### ISSUE THREAD

**Issue by tomerr90** [AdoptOpenJDK/jitwatch#374]
I have a project Im build and compiling using maven with the compiler and assembly plugins.
Running on MacOS.
I added the following to source locations:
- Contents/Home/lib/src.zip (in the jdk folder)
- target/classes (for my project's classes)

But whatever I try it just wont read the source.
Tried adding the relevant class file and java file directly (after changing the code to have the class in the default package) - Didnt work.
Tried adding target/myPackage which contains the class files, also didnt work.
Weird thing is that I cant see the source for java/jdk/sun classes either.

Running with: java --enable-preview --add-modules=jdk.incubator.vector -jar ui/target/jitwatch-ui-shaded.jar

**Comment by tomerr90** [comment]
Ah, sorry, I was sure I added the Java version.
JDK 17, MacOS Ventura 13.4.

**Comment by chriswhocodes** [comment]
Please can you try running one of the sandbox examples and see if that works for you? Could you upload the jitwatch.out logfile (or email to me chris@chrisnewland.com) ? Thanks.

**Comment by tomerr90** [comment]
Sent.
Yeah, like I wrote above, the sandbox example does work for some reason.

**Comment by chriswhocodes** [comment]
Hmm, nothing helpful in the log. Please can you show me your config window?

**Comment by tomerr90** [comment]
<img width="638" alt="image" src="https://github.com/AdoptOpenJDK/jitwatch/assets/37086811/5d31a450-18f6-40f9-a3bd-95038c93708b">

**Comment by chriswhocodes** [comment]
Hi are you sure your source files are in target/classes?

**Comment by tomerr90** [comment]
<img width="787" alt="image" src="https://github.com/AdoptOpenJDK/jitwatch/assets/37086811/bc109325-11a1-4a24-b70a-aeceeecf48bc">

**Comment by chriswhocodes** [comment]
Hi, the source pane is for mounting .java files. Class files and jars are mounted in the lower section of the config pane.

**Comment by tomerr90** [comment]
I tried that as well but added the wrong "level", should have added src/main/java.
It works now, thank you so much!

**Comment by chriswhocodes** [comment]
Glad I could help 😀
