### ISSUE TITLE
Gradle build is broken.

### ISSUE THREAD

**Issue by swpalmer-cl** [AdoptOpenJDK/jitwatch#375]
The Gradle wrapper is using an ancient version of Gradle (5.5) that doesn't run on modern Java:
```
❯ ./gradlew clean build run

...

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
> Exception java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7 [in thread "Daemon worker"]
```

Using a recent version of Gradle, the 'findbugs' plugin is not found:
```
❯ gradle clean build run 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/scott/dev/OpenSource/jitwatch/build.gradle' line: 17

* What went wrong:
Plugin [id: 'findbugs'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin. For more available plugins, please refer to https://docs.gradle.org/8.2/userguide/plugin_reference.html in the Gradle documentation.)
- Plugin Repositories (plugin dependency must include a version number for this source)
```

Since the build instructions don't mention a maximum Java version, only mentioning JDK 11+, I consider this a bug.
My attempts to build were using OpenJDK 17.0.7,  with the Gradle wrapper and with Gradle 8.2.

**Comment by chriswhocodes** [comment]
Hi Scott, thanks for reporting.
JITWatch uses maven as its build system, the gradle build was a contribution but I won't be maintaining it.
I'd be happy to receive a PR to fix the gradle build but if not I will remove it and leave maven as the only build system.
Kind regards,
Chris

**Comment by chriswhocodes** [comment]
Removed unmaintained gradle build system leaving maven as the only build system.
